### ISSUE TITLE
Improve documentation: gui Frame

### ISSUE THREAD

**Issue by Conengmo** [pyglet/pyglet#1007]
I'm building a media application with Pyglet and really enjoying what the package can do! My application has a 'control panel' with some gui widgets like buttons. I had an issue where pressing one button would also trigger its neighbor. After some investigation I'm now pretty certain it's because of the `Frame` the buttons are in: the default cell size was larger than the distance between the buttons.

I couldn't find any documentation on how to use the `Frame` class. I'm not sure how I even came to use it, maybe this example? https://github.com/pyglet/pyglet/blob/master/examples/gui/widgets.py

Would it help to add something about `Frame` to the gui api reference? https://pyglet.readthedocs.io/en/latest/modules/gui.html 

And was my conclusion about cell size correct? In that case it would be useful to add a line to the docstring warning users to make the cell size smaller than the distance between widgets.

I can help with this, just wanted to check first what is useful.

**Comment by benmoran56** [comment]
Hello Frank, 

I'm glad that you're enjoying pyglet.  The API docs could certainly use some work for this module. PRs are always welcome! 

The Frame class is intended to eventually work similar to other toolkits, such as tkinter, but so far it only implements a simple spatial hash. (This is what the `cell_size` argument is for, to control the spatial hash sizes). 

The Frame essentially acts like a filter between Window events, and your various widgets. Instead of every widget receiving every mouse event from the Window, it only sends these events to widgets that are within the nearby "cells".  Having the cell size too large will just send events to more widgets, but that won't cause any issues. The widgets themselves still do a AABB check to decide if they want to handle the event or not.

Do don't actually need a Frame at all, if you have relatively few widgets - you can just do `Window.set_handlers(my_widget)` for each one. 

Are you able to provide a small code sample that shows the issue?

**Comment by Conengmo** [comment]
Thanks for the quick response! Appreciate it.

I didn't know about `Window.set_handlers(my_widget)`, thanks!

I made a Gist to demonstrate the issue: https://gist.github.com/Conengmo/2bddd20b3948635e8a3d40771dfc2ffb. Clicking a button triggers the callback of both buttons depending on where you click. If you reduce the `cell_size` of the `Frame` to, say, 5, the issue goes away.

And in making this example I think I also found what was going wrong: I overloaded the `on_mouse_release` method, so when I called my own callback, the `_pressed` variable was not being checked.

I also found out how I should do it instead: replace the overloaded method with `self.set_handler("on_release", callback)` in the init.

I updated the Gist to show both examples, in case somebody else encounters the same problem. 

Thanks @benmoran56! I'll close the issue since the issue is resolved. But I'll make a PR later to add `Frame` to the docs.
