### ISSUE TITLE
Segment fault when packed with pyinstaller on linux

### ISSUE THREAD

**Issue by zhengxyz123** [pyglet/pyglet#1049]
Take this simple program as an example:
```python
# test.py
from pyglet import app, clock, window

win = window.Window(400, 300, "test")

@win.event
def on_activate():
    print("event: on_activate")

@win.event
def on_deactivate():
    print("event: on_deactivate")

@win.event
def on_expose():
    print("event: on_expose")

@win.event
def on_draw():
    win.clear()

if __name__ == "__main__":
    clock.schedule_interval(win.draw, 1 / 60)
    app.run()
```

Then run:
```bash
pyinstaller -F test.py
```

Then I run `python test.py` and `test`(generated by pyinstaller) and apply following action twice:

1. Open the window
2. Minimize the window
3. Show the window

They have different behaviors:
```bash
$ python test.py 
event: on_expose
event: on_expose
event: on_activate
event: on_expose
event: on_deactivate
event: on_expose
event: on_activate
$ ./dist/test 
event: on_expose
event: on_expose
event: on_activate
event: on_expose
event: on_deactivate
[segment fault occurred after deactivate the window]
```

- - -

The following information may be useful:
```
           PID: 40211 (test)
           UID: 1000 (jason)
           GID: 1000 (jason)
        Signal: 11 (SEGV)
     Timestamp: Thu 2024-02-15 20:22:25 CST (1min 23s ago)
  Command Line: ./dist/test
    Executable: /home/jason/Desktop/mystery/dist/test
 Control Group: /user.slice/user-1000.slice/user@1000.service/app.slice/app-codium-f871a7386bc04ed0912f3571bb3c89d4.scope
          Unit: user@1000.service
     User Unit: app-codium-f871a7386bc04ed0912f3571bb3c89d4.scope
         Slice: user-1000.slice
     Owner UID: 1000 (jason)
       Boot ID: c5b33364fbd648119cd60c079d88ed29
    Machine ID: 52078f282d23400cb95de4b0fdd5f887
      Hostname: mydebian
       Storage: /var/lib/systemd/coredump/core.test.1000.c5b33364fbd648119cd60c079d88ed29.40211.1707999745000000.zst (present)
  Size on Disk: 50.6K
       Message: Process 40211 (test) of user 1000 dumped core.
                
                Stack trace of thread 40211:
                #0  0x00007f43e5fd1e2c __pthread_kill_implementation (libc.so.6 + 0x8ae2c)
                #1  0x00007f43e5f82fb2 __GI_raise (libc.so.6 + 0x3bfb2)
                #2  0x0000000000404204 n/a (/home/jason/Desktop/mystery/dist/test + 0x4204)
                ELF object binary architecture: AMD x86-64
```
and output from `dmesg`:
```
[353795.150103] test[40212]: segfault at 8 ip 00007f27a5840620 sp 00007ffcd6e79968 error 4 in libX11.so.6.4.0[7f27a580b000+8b000] likely on CPU 3 (core 3, socket 0)
[353795.150158] Code: 16 b5 fc ff 66 0f 1f 44 00 00 48 85 ff 74 13 48 83 7f 08 00 74 0c 48 8b 07 ff 60 08 66 0f 1f 44 00 00 c3 0f 1f 80 00 00 00 00 <48> 83 7f 08 00 74 09 48 8b 07 ff 60 10 0f 1f 00 c3 66 66 2e 0f 1f
```
and from [pyglet.info](https://github.com/pyglet/pyglet/files/14296946/info.txt).

This issue was found both on KDE(Wayland) and KED(X11).

**Comment by benmoran56** [comment]
I saw this as well on the latest PyInstaller. It might be a bug introduced in some recent version.

**Comment by zhengxyz123** [comment]
I did a rough skim of pyinstaller's issues and didn't find a similar problem.

The error seems to occur in the underlying shared libraries, does that mean there is no solution with python?

**Comment by benmoran56** [comment]
Nuitka does not crash. Pyinstaller also did not crash in the past. Unfortunately, older PyInstaller does not support the latest Python versions, but it's worth to test previous versions.

**Comment by zhengxyz123** [comment]
I found that `pyinstaller==5.13.0` won't crash.

**Comment by benmoran56** [comment]
That's good information.
I see in the v5.13 release notes, there is a message about "breaking changes in v6". https://github.com/pyinstaller/pyinstaller/releases/tag/v5.13.0
However, none of these changes should cause any pyglet issues. It's probably a new bug that was introduced since then. 

Unfortunately v5.13 doesn't support Python 3.12, but it's good for a temporary solution.

**Comment by zhengxyz123** [comment]
So, you think this is a bug in the new version of pyinstaller. Then creating a new issue is a good option.

**Comment by rokm** [comment]
This looks like combination of regression in PyInstaller 6.x, and a bug in `pyglet`.

The PyInstaller-side of the problem is that with PyInstaller 6.x, `locale.getlocale()` in frozen application incorrectly returns `(None, None)`, in contrast to unfrozen python and PyInstaller 5.x.

On `pyglet` side, this means that `_have_utf8` is `False`:

https://github.com/pyglet/pyglet/blob/096766f05bd0142c35d51bef2aa16f215be8e05c/pyglet/window/xlib/__init__.py#L56

which results in `self._x_ic` initialization being skipped here:

https://github.com/pyglet/pyglet/blob/096766f05bd0142c35d51bef2aa16f215be8e05c/pyglet/window/xlib/__init__.py#L387-L406

and consequently `XUnsetICFocus` being called with NULL pointer here

https://github.com/pyglet/pyglet/blob/096766f05bd0142c35d51bef2aa16f215be8e05c/pyglet/window/xlib/__init__.py#L1583

causing the segfault.


So this can be triggered with unfrozen python as well, for example trying to run the sample program from original report with non-UTF8 locale set, e.g., `LANG=sl_SI.ISO8859-2`.

**Comment by benmoran56** [comment]
Thanks for taking the time to look into this. The non-utf fallback should be easy enough to fix on the pyglet side.

**Comment by zhengxyz123** [comment]
By using `pyinstaller==6.5.0`, this issue was solved.
