### ISSUE TITLE
explicit application control over event queuing strategy

### ISSUE THREAD

**Issue by matanox** [pyglet/pyglet#1117]
Currently, both `Window.dispatch_event` and `pyglet.app.platform_event_loop.post_event` entail non-determinism for the caller:

+ `Window.dispatch_event` may either immediately execute the event callbacks or queue their execution.
+ `app.platform_event_loop.post_event` says that if called from the main thread: 
    > the event may be dispatched within the same runloop iteration or the next one; the choice is nondeterministic 

For the caller these are different non-determinisms on the same general axis. 

Are there arguments to be passed to `pyglet.app.platform_event_loop.post_event` that can assure one behavior or the other?
Or is this an enhancement request?

**Comment by matanox** [comment]
I apologize that this is indeed related to my https://github.com/pyglet/pyglet/pull/1116, but it runs deeper since `post_event` too is non-deterministic in that regard.

**Comment by matanox** [comment]
Lastly on this, is there any guarantee to the order of event handling among raised events? 
I notice that any event raised through `app.platform_event_loop.post_event` will get to the front of the line, being handled first after the flow of execution returns to the event loop from the callback that raises it. It will be handled before any and all events scheduled for every clock tick (`schedule()`) and before those scheduled with `schedule_interval`. That's actually useful, however is that always the case? 

Or otherwise is there any set hierarchy to the order of the handling of events being raised through all of the different ways ― `schedule_once`, `schedule_interval`, `schedule`, `post_event` and any other ways that events may be internally raised in response to OS events? I was sifting through the source but it's a little elusive if `self.queue` is always the same type and how it is being popped for exeuting events from it ... my debugger fails entering its methods ... is there a set project philosophy for how raised events are being ordered for handling across these different methods of scheduling and raising?

**Comment by benmoran56** [comment]
I've had a difficult time understanding your issues, but I think I now understand the confusion here: 
pyglet's `event` module does not implement an event queue.
The handlers/callbacks are directly attached functions.  When you call `EventDispatcher.dispatch_event(...)`, it directly calls the attached functions in the order they are attached (pushed to the event stack). 
```py
disatch_event(...):
     some_handler()
     another_handler()
```
If one of these handlers dispatches another event, then that also happens directly. This is by design, and is used throughout pyglet's codebase. For example, you can see in the `input` module how events start from the `Control` objects and then get handled by the higher-level `Joystick`/`Controller` objects, which then dispatch their own events. These events are all directly chained, and a call to `EventDispatcher.dispatch_event(...)` does not return until **all** of it's handlers (and anything they might call) return.

If you need an "event queue", then you can build one on top of pyglet's callback/handler event system. Just attach a handler to each event, and then place something in the queue, as is appropriate for what you want to accomplish. You can then iterate over this queue and process them as you need. 

Regarding the `app.platform_event_loop.post_event` method,  is not intended to be called from the main thread. It can be, but there isn't much use case. It exists as a way for threaded code to ensure events are dispatched from the main thread. If you use this from the main thread, you are just potentially delaying the dispatch - it still gets dispatched in the exact same way as directly dispatching it, just potentially later. A Python `queue` _is_ used internally for inter-Thread passing but it's just an implementation detail, and does not change anything into an "Event Queue" as per the way it means in in programming patterns. 

Hope this helps!

**Comment by benmoran56** [comment]
The only way to really answer your questions is to look at the source code. We do not have a design doc, and I do not have the linguistic ability to explain here. Hopefully the code is straightforward enough to answer your questions. In short, it's a combination of ``poll`` and ``select`` (in these Linux examples). Other platforms work similarly, but not identically. 
https://github.com/pyglet/pyglet/blob/master/pyglet/app/base.py#L35
https://github.com/pyglet/pyglet/blob/master/pyglet/app/base.py#L50
https://github.com/pyglet/pyglet/blob/master/pyglet/app/xlib.py#L65

It _might_ produce a consistent result if you post these events from the main thread, but that is not designed or intended to be used that way. When posting from another thread, you can see from the code why it might fall before or after the poll/select blocks.

**Comment by matanox** [comment]
Thanks a lot. I stopped abusing the event system for this purpose after reading here.
