### ISSUE TITLE
Local paths in wgl.h

### ISSUE THREAD

**Issue by onitake** [pyglet/pyglet#1133]
**Describe the bug**
The (apparently machine-generated) file https://github.com/pyglet/pyglet/blob/master/pyglet/gl/wgl.py contains a lot of references to local paths. This may or may not be a privacy issue, but it should be probably be addressed in the generator script.

It's also noteworthy that the backslashes in the multiline strings can generate syntax warnings in recent Python versions.

**System Information:**
N/A

**How To Reproduce**
N/A

**Comment by benmoran56** [comment]
Thanks for opening the ticket. That file was last regenerated back in 2007 by one of the original authors, so I don't think there is any concern about the file paths in the comments.  :slightly_smiling_face: 

Still, no harm in removing them. This spec doesn't change, so it's not useful to keep the comments. 
It turns out that in addition to the back-slashes, there were even tab characters in there, so I've stripped those out as well.
