### ISSUE TITLE
Depth test on shapes

### ISSUE THREAD

**Issue by Mathorga** [pyglet/pyglet#1247]
Hey,

I've been using Pyglet for the last few years making 2D games and I've always been using OpenGL's native depth sorting for sprites by enabling GL_DEPTH_TEST and using each sprite's z coord. Everything works great, it's very fast and I can change the sort order dynamically very easily. This is very useful when working wirh top down games for example.
I can't seem to work with shapes this way though: I wasn't able to find a way to change the z coord of any shape. The z coord is not part of the constructor arguments (as it is for sprites) and it looks like there's no setter for it.
Am I missing something? Is there a way to sort shapes along with sprites during rendering using their own z coord?

Thank you very much in advance

**Comment by benmoran56** [comment]
Hi @Mathorga, 
I'm glad you're enjoying pyglet. We have had other requests for adding `z` ordering to Shapes, and we have been considering it.
I had some time, so I made a quick PR into the `development` branch (upcoming pyglet 2.1) that adds a Z setter/getter to all shapes. 
https://github.com/pyglet/pyglet/pull/1248/files

I opted not to touch the positional arguments, because it would complicate things for people that don't care about the Z position. For example: making a Line would need `x, y, z, x2, y2` which makes it a bit messy.

This is a fairly low change addition, so I think we can get this into the 2.1 release.

**Comment by Mathorga** [comment]
Thank you! I'll keep a close eye on your PR!

**Comment by benmoran56** [comment]
This was just merged in, and is included in the  v2.1.rc3 release. 
You can update to that via PyPI with the "--pre" argument: `pip install --upgrade pyglet --pre`
Please be aware that the 2.1 release has some breaking changes, such as switching to using "thickness" instead of "width" in the shapes module. It's not yet released, but you can see the migration guide for a list of breaking changes: https://pyglet.readthedocs.io/en/development/programming_guide/migration.html
