### ISSUE TITLE
[question] What's the plan for pyglet 1.4 - 1.5

### ISSUE THREAD

**Issue by ccanepa** [pyglet/pyglet#127]
- Next release(s) would be 1.4.x ? When  the next release is planed?
- When 1.5 kicks in ?
- 1.5 will break compatibility with 1.4? any place to follow API changes?

**Comment by benmoran56** [comment]
Hi Claudio, 

1.5 will be identical to 1.4, except Python 2 support has been removed. This includes stripping out all usage of the `future` module, and removing Python2 codepaths. No API changes are planned. Small new features or classes may be added if they're useful, but mostly it will receive only bugfixes.

The idea is to get the existing codebase into a more maintainable form, because v2.0 is where the real changes will happen. This is because pyglet 2.0 will be rebasing from OpenGL 2.0, to 3.3+. This will be a big change, so the v1.5 series will remain available alongside 2.0.

**Comment by einarf** [comment]
I guess if we really want to be pedantic 1.5 should have been 2.0, but 2.0 was already taken for the fixed pipeline version months ago. 😃 

.. but looking at the download metrics there is a very small user base on py2. Pip will also not install 1.5 or 2.0 versions, so it should not break things.

**Comment by benmoran56** [comment]
Hi Claudio, I'm going to close this for now. Please reopen it if you want to follow up. 

Before 2.0 is released, there will be some update to the readme, docs to talk about the changes.
