### ISSUE TITLE
NoSuchConfigException on Raspbian

### ISSUE THREAD

**Issue by thismachinekillszombies** [pyglet/pyglet#135]
I'm just doing some experimenting using pyglet on Raspian. To get antialiasing working on gl I've tried to change the window config to...

Config(sample_buffers=1, samples = 4)

...and I get NoSuchConfigException.

As far as I understand this isn't a hardware limit on the Pi, because I've modified the hello_triangle sample code that ships with Raspbian (/opt/vc/src/hello_pi/) and changed the settings of the DISPMANX egl window to have 1 sample buffer and 4x sampling and it works fine.

I've spent an afternoon Googling and can't really find anyone else having this problem, so is it a pyglet problem or am I completely misunderstanding something (which is entirely possible)?

**Comment by benmoran56** [comment]
Thanks for opening the ticket. The config you've created is a "template" config, meaning it's not complete. This part is OK.  What *should* happen is that when you pass it to the Window, pyglet uses your template config to create a fully completed config to use on Window creation. It doesn't seem to be doing that, so this might be a bug. I'll have a look into this later to confirm. 

In the mean time, you can manually create a completed configuration. It's a bit roundabout, but this should work: 
```py
config = pyglet.canvas.get_display().get_default_screen().get_best_config()
print(config)  # to have a look at what the default values are
config.sample_buffers = 1
config.samples = 4
```
Could you give that a try?
Thanks!

**Comment by thismachinekillszombies** [comment]
Thanks for the response. That works, in that it creates the window without giving the exception, and when I look at the config extracted from the window sample_buffers and samples have the new values.

It doesn't seem to be doing much anti-aliasing though, but that's probably because I'm misunderstanding something about OpenGL. I'll continue experimenting and get back to you if I think it's a Pyglet problem.

By the way, when I created a template config with values (sample_buffer = 0, samples = 0), that didn't cause the NoSuchConfigException.

Thanks again!

**Comment by benmoran56** [comment]
Great, I'm glad that at least doesn't crash. The template config with zero values is probably just detected as an empty template, so it's not being used. I'll have a look at this in more detail and see if it can be fixed. Lets leave this issue open until then. 

As for the Raspberry Pi, the OpenGL drivers will lie about certain capabilities in order to let some things run. Maybe it's possible that this type of anti-aliasing isn't fully supported? 

There is some code in the test suite for visually comparing anti-aliasing modes. You would need `pytest` installed to run it: https://github.com/pyglet/pyglet/blob/master/tests/interactive/window/test_window_multisample.py
This should work as expected on your Desktop. You could then try it on the Pi to see if it's actually supported in the driver or not.

**Comment by benmoran56** [comment]
So I took a dive into this, and it turns out that [glXChooseFBConfig](https://www.khronos.org/registry/OpenGL-Refpages/gl2.1/xhtml/glXChooseFBConfig.xml), which is the GLX function responsible for matching the Config templates on X, may refuse to match any configs containing multisampling arguments. Posts on the Khronos forums indicate that the multisampling spec is not really clear, which would explain why that function doesn't match anything.

It may just be that you need to use the workaround I posted earlier, which is to get a default configuration, and then "tack on" the additional parameters. This is not guaranteed to be a valid configuration if you do it this way, but as long as it doesn't crash you should be fine.

**Comment by benmoran56** [comment]
I'll go ahead and close this for now since we found a workaround, but please do open an additional ticket if you want to follow up! 

Thanks, 
-Ben

**Comment by thismachinekillszombies** [comment]
Sorry Ben, I got distracted on another project so didn’t have chance to say thanks for looking into this and responding so quickly on my original query.


R.
