### ISSUE TITLE
pyglet 1.4.10 - spureous traceback quiting astraea.py (and all cocos tests)

### ISSUE THREAD

**Issue by ccanepa** [pyglet/pyglet#142]
quiting with ESC or pressing the quit menuitem
```
(py38-cocos2020) D:\dev\pyglet-2019\examples\astraea>python astraea.py
Error in sys.excepthook:

Original exception was:

(py38-cocos2020) D:\dev\pyglet-2019\examples\astraea>
```
Quiting with the window's close button
```
(py38-cocos2020) D:\dev\pyglet-2019\examples\astraea>python astraea.py
(py38-cocos2020) D:\dev\pyglet-2019\examples\astraea>

Impacts the cocos library because 200+ tests now are listed as having tracebaks

Note that all the cocos's `test\test_*` don't use sound, so probably unrelated to #113

 win7, py3.8, cocos b490c, pyglet 1.4.10

**Comment by ccanepa** [comment]
The problem does not show with py37

**Comment by ccanepa** [comment]
Fixed for cocos.

You can fix astraea in similar way changing sys.exit() to win.on_close()

**Comment by benmoran56** [comment]
Thanks for the feedback Claudio. 
I've looked it over, and decided to try `pyglet.app.exit` (since that's what it really should have been in the first place). This *should* hopefully fix it as well, but I haven't been able to duplicate this error on my machines. 

I'm going to close this for now but please let me know if you still see any issues!

**Comment by ccanepa** [comment]
FYI pyglet.app.exit gives the exception in astraea, while win.close is clean.
