### ISSUE TITLE
Pyglet media player seek() mangles sound?

### ISSUE THREAD

**Issue by davidlondonuk** [pyglet/pyglet#161]
Hi,
Thanks for the advice on the pyglet.clock.tick() to get the playing playing properly, it works great now - except for seek().

I have made sure I check the player is playing before attempting seek, but it just mangles the sound. It sounds like the player has just got lost in the source somewhere. I am using GLib.time_out(250, self.tick) im milliseconds to call tick() which just has:

pyglet.clock.tick()
return True

I'm using Ubuntu 18.04 and porting a tkinter music-player to pygobect, so far so good, pyglet does what it says on the tin apart from being able to fast-forward or rewind the track source.

Thanks for any help.

**Comment by benmoran56** [comment]
Is using StaticSources an option for your project? You might also want to tick faster, such as 0.1 seconds and see if that has any effect.

**Comment by benmoran56** [comment]
Hi, were you able to try those suggestions?

**Comment by benmoran56** [comment]
Closing this now due to lack of response, but please follow up with a new ticket if needed.

**Comment by fladd** [comment]
Same issue here on MacOS. The problem seems to be a mismatch in samplerate (i.e. the source is often played back slower after seeing), which self-corrects itself after a couple of seconds letting it play.

The rate of ticking the clock does not seem to influence this (happens with 100ms, 10ms and 1ms).

Any idea what seems to be the problem?

**Comment by fladd** [comment]
This also happens in examples/media_player.py btw...

**Comment by benmoran56** [comment]
@fladd Lets follow up in the other ticket you opened.
