### ISSUE TITLE
schedule_interval didn't works fine.

### ISSUE THREAD

**Issue by ryback08** [pyglet/pyglet#173]
Hello, 

I'm using pyglet 1.5.2 on python 3.7 on windows 10 with WinPython
schedule_interval seems to be bug, 

```
import pyglet
window = pyglet.window.Window()

@window.event
def update(dt):
    print(1/dt)
    return

pyglet.clock.schedule_interval(update, 1./60)
pyglet.app.run()
```

Result :
```
59.31028895320312
52.27950127028808
59.8641371434697
33.134553623719256
0.0959756349496432
55.0476492451857
32.04825287507385
32.04229377707945
59.87269986300499
```

**Comment by caffeinepills** [comment]
I just tested with python 3.7 and python 3.6, on Windows 10 with 1.5.2 and behavior is as expected. 
```
50.97801318291417
59.9401797006588
59.38877077122259
59.035710701403254
58.97373899402599
59.93083981085826
59.92078472259672
59.503974865521
59.01132427312806
59.564228107168006
59.722885809842204
57.55958856406101
59.992680892930935
59.72930678166555```

Possibly an installation issuem or program issue with WinPython?

**Comment by benmoran56** [comment]
This type of test won't be accurate in most terminals, because printing at 60fps won't work reliably. Instead, you can make a `pyglet.text.Label` and update the label text instead. 

That said, we do have unit tests for the scheduling functions, and they do pass. If you want to run the test suite on your own machine to confirm, you can find the scheduling tests at `tests/unit/test_clock.py` in the repository.

**Comment by ryback08** [comment]
@caffeinepills, you right, it is my version of winpython (3.7.4)...grrrrr Reinstall the lastest and the fps works perfectly.
@benmoran56.  I didn't try to run "tests/unit/test_clock.py", error at "from tests import mock".

Thanks to you two
