### ISSUE TITLE
Feature Request: Basic Shape Classes

### ISSUE THREAD

**Issue by nbroderick-code** [pyglet/pyglet#175]
Pyglet supports gl vertices which means it is very powerful, and very flexible.

However, dealing with them feels very 'low level' when compared with the rest of pyglet.
Like machine code or something.

Could convenience classes similar (at least in spirit) to the one below be added for the gl impaired coders among us?

```
class VertexRectangle:
    def __init__(self, x, y, width, height, color):
        self.x = x
        self.y = y
        self.width = width
        self.height = height
        self.color = color
        r = color[0]
        g = color[1]
        b = color[2]
        self.vertex_list = pyglet.graphics.vertex_list(4, 'v2f', 'c3B')
        self.vertex_list.vertices = [x, y,
                                   x + width, y,
                                   x + width, y + height,
                                   x, y + height]
        self.vertex_list.colors = [r, g, b,
                                   r, g, b,
                                   r, g, b,
                                   r, g, b]
        self.draw_mode = pyglet.gl.GL_QUADS

    def draw(self):
        self.vertex_list.draw(self.draw_mode)

    def move_relative(self, dx, dy):
        self.__init__(self.x+dx, self.y+dy, self.width, self.height, self.color)

    def move_absolute(self, x, y):
        self.__init__(x, y, self.width, self.height, self.color)

    def width_absolute(self, w):
        self.__init__(self.x, self.y , w, self.height,
                      self.color)

    def width_relative(self, dw):
        self.__init__(self.x, self.y, self.width + dw, self.height,
                      self.color)

```

**Comment by agricolab** [comment]
Cocos has a set of 2d primitives already implemented https://github.com/los-cocos/cocos/blob/master/tools/primitives.py

**Comment by nbroderick-code** [comment]
Fair, but don't you think it's something that should be available in vanilla pyglet?
Many of the pyglet "competitors" have this feature by default.

**Comment by agricolab** [comment]
I apologize if the the link to cocos appeared as an attempt for deflection, it was meant as a suggestion. I should have been more verbose in my reply, sorry.
I do agree this feels at odds with the high-level interface implemented  for other aspects, e.g. audio or input devices, but i also understand that  2D primitives are a rare use-case for what seems to be the goal of pyglet, i.e. *games and other visually rich applications*. Considering this, i could understand if there is no priority to get it into vanilla pyglet. But when i started using pyglet, i was also missing it. I would therefore very much welcome a (variable nodes) polygon and a circle (the rest could probably be easily wrapped from that), although i am personally not in need anymore.

**Comment by einarf** [comment]
My first thought is that these would have to be compatible with batches somehow so you can build large lists of them and draw in a single batch. I just foresee people looping over 1000 triangles drawing them individually tanking performance 😄

**Comment by nbroderick-code** [comment]
agricolab, No worries. :)

How rare are they really, though? Loading bars, health point bars, drawing lines between objects to show they are hierarchically connected, **I'm sure we could come up with a huge list of visually rich software that uses basic geometric shapes.**

einarf, **I believe they already are compatible with batches** if I'm reading the docs correctly.
see
vertex_list = batch.add()
on 
https://pyglet.readthedocs.io/en/latest/programming_guide/graphics.html

**Comment by benmoran56** [comment]
In the past there has been some resistance to adding something like this to core. The principle behind adding features to pyglet is to avoid becoming bloated, which I think is a good goal.

That said, I do think something like this could be useful. We would probably want to have an API that is similar to the Sprite class, with rotation and anchor points, etc.  I'm not positive if we want to add it to the main project, but at the least it could be a useful addition to /contrib or even /examples in the repository. If we get more feedback, and people want it in master, then we can of course consider adding it.

**Comment by kcmw3e** [comment]
I've got a thing that's pretty similar to all this. It's a little inefficient at the moment, but it's got some of the core ideas there. It could be useful for what you're looking for @nbroderick-code. It's still a WIP so there's a few bugs I'm sure.

Anyway, it's uploaded to my github at: [https://github.com/kcmw3e/flippant-piano](url)

(Also, I'm new to github so if I've done something wrong on my repository or here in the comments, sorry about it.)

**Comment by nbroderick-code** [comment]
It's always good to see other users solution to this issue!

**Comment by benmoran56** [comment]
What shapes would be considered most important? Rectangle, Circle, and Line? Anything else?

**Comment by agricolab** [comment]
Recarding the circle it world be great to be able to have an `angle` parameter to define a circle sector. this would allow to plot half-circles or similar shapes, and the full circle would be a special case.

**Comment by kcmw3e** [comment]
So maybe a big suite of shapes like circle, rectangle, line, arc, and perhaps a simple/convex polygon (as described [here](http://www.glprogramming.com/red/chapter02.html#name2). Maybe each shape could even take an optional angle argument to define some rotation of the specific shape. My comment above has good examples of what I mean by this, though it's not perfect/fully implemented at the moment.

Also, batches don't presently don't agree with polygons very well as they are now. If a batch's vertex lists are drawn with GL_POLYGON mode, they are all connected, so the workaround I have now is to add vertex lists of triangles and draw them as GL_TRIANGLES instead.

**Comment by benmoran56** [comment]
@kcmw3e I edited your earlier post to fix your link. Nice work! It seems pretty featured already. 
As for your comment about GL_POLYGON, that also applies to things like GL_TRIANGLE_FAN as well, for the same reason. Doing as you said and using GL_TRIANGLES is the only solution at the moment, since it would take a bit of internal work to make them work with Batching. (That might be revisited for pyglet 2.0). Maybe we should throw a warning if you try adding them to a Batch in pyglet 1.5.x... 

I have a module mocked up already with Circles and Rectangles, which mimics the Sprite API to an extent. There is support for modifying position, color, opacity, and anchor positions. The Rectangle also supports rotation. You can find that here if you want to have a look, or contribute: 
https://github.com/pyglet/pyglet/blob/pyglet-1.5-maintenance/experimental/shapes.py 

@agricolab Would what you're describing be something like an Arc? As in, you specify a radius, start & end angles? Sorry I'm not very good with geometry, but I think I know what you mean.

**Comment by agricolab** [comment]
yes.

**Comment by benmoran56** [comment]
I've added a Line class, which are really just thin quads (making any thickness possible). This brings a total of three shapes so far: Circles, Rectangles, and Lines. 

I still need to figure out the math for making an Arc class. If anyone can have a look and comment on the API, that would be great.

**Comment by agricolab** [comment]
Cocos2D is apparently using [gluPartialDisk directly](https://github.com/los-cocos/cocos/blob/master/tools/primitives.py#L155 ) for arc plotting. This seems to be not an option if i understand your earlier [comment](https://github.com/pyglet/pyglet/issues/175#issuecomment-613371945) correctly.

The segments argument for [circle](https://github.com/pyglet/pyglet/blob/pyglet-1.5-maintenance/experimental/shapes.py#L318) implementation are due to the breaking down the circle into triangles, right? A circle spans from 0° to 360°, and similarly, an arc spans between to angular end points, e.g. `arc_limits_in_deg = (0, 90)` or `arc_limits_in_deg = (330, 210)`. With these endpoints, order is important, i.e. `(0, 90) != (90, 0)`, as the first spans a quarter, while the second spans three quarters of the circle. Then, this implementation might work:
``` python
import math
# class arguments
arc_limits_in_deg = (0, 90)
segments = 25
x = 0
y = 0
r = 1
# calculations
arc_lim = []
for a in arc_lim_in_deg:
   # we perform modulus conditional on >360, because otherwise, 
   # 0 and 360 would span a distance of 0° and not 360°
    if a > 360:
        a %= 360
    arc_lim.append(math.radians(a))
# we calculate the angular distance, taking the order of endpoints into account
arc_dist = arc_lim[1] - arc_lim[0]
#  but if the arc passes over 0°, e.g. from 330° to 60°,
# we have to take this jump into account and calculate the distance piece-wise.
if arc_dist < 0:
    arc_dist = math.pi * 2 - arc_lim[0] + arc_lim[1]
# subsequently, we divide the full  angular distance into segments for triangular approximation
tau_segs = arc_dist / segments
# and add endpoints
points = []
for i in range(0, segments + 1):
    arc_p = arc_lim[0] + tau_segs * i
    while arc_p > math.pi*2:
        arc_p -= math.pi*2
    p = (x + (r * math.cos(arc_p)), y + (r * math.sin(arc_p)))
    points.append(p)
```

**Comment by einarf** [comment]
There are arc shapes in arcade. 
https://github.com/pvcraven/arcade/blob/07a2498c56bd50703dea4e79a4ecc5de2bfdfd1c/arcade/draw_commands.py#L43

I'm making geometry shader version this weekend at least. It's basically just a circle. The number of segments decides the resolution of the angles. As long as the rounding is done right (odd/even rounding trap) it should be cake.

**Comment by kcmw3e** [comment]
Here's some thoughts. . .

For Circles:
Add an optional parameter to circle called angle --> `def __init__(self, x, y, radius, segments=25, color=(255, 255, 255), batch=None, group=None, angle = math.pi * 2):`
and then change line 339 (`tau_segs = math.pi * 2 / self._segments`) to `tau_segs = self._angle / (self._segments-1)`. This will allow for specifying a portion of the circle to be drawn (from angle 0 to specified angle). Then a method called rotate (or another parameter) could be used to rotate the slice of the circle to a desired angle.

For arcs:
Keep the same code as for circle but change this -- lines 346 to 349 should make points that can be drawn as GL_LINES, so instead of triangular points, just change line 348 (`triangle = x, y, *points[i-1], *point`) to `*points[i-1], *point`. This essentially doubles-up each point with the previous one, and lets GL_LINES draw the arc similarly to the way GL_TRIANGLES draws the circle. There is a caveat: I just ran through that briefly, so the assigning of same-size sequences to the vertex_list is messed up (so some constants need to be adjusted on lines 328 and 354 from a 3 to a 2). Also, this modification is resulting in a closed arc at the moment, so a further modification should be made (or a parameter to be specified) to decide whether to close the arc or leave it open.

Here's the arc code: (the lines that I changed are closed up by ####'s -- hopefully I got them all)
```class Arc(_Shape):
#########################
    def __init__(self, x, y, radius, segments=25, color=(255, 255, 255), batch=None, group=None, angle = math.pi * 2):
#########################
        self._x = x
        self._y = y
        self._radius = radius
        self._segments = segments
        self._rgb = color
#########################
        self._angle = angle
#########################

        self._batch = batch or Batch()
        self._group = ShapeGroup(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA, group)

#########################
        self._vertex_list = self._batch.add(self._segments*2, GL_LINES, self._group, 'v2f', 'c4B')
#########################
        self._update_position()
        self._update_color()

    def _update_position(self):
        if not self._visible:
            vertices = (0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
        else:
            x = self._x + self._anchor_x
            y = self._y + self._anchor_y
            r = self._radius
#########################
            tau_segs = self._angle / (self._segments-1)
#########################
            # Calcuate the outer points of the circle:
            points = [(x + (r * math.cos(i * tau_segs)),
                       y + (r * math.sin(i * tau_segs))) for i in range(self._segments)]

            # Create a list of doubled-up points from the points:
            vertices = []
            for i, point in enumerate(points):
#########################
                line_points = *points[i-1], *point
                vertices.extend(line_points)
#########################
        self._vertex_list.vertices[:] = vertices

    def _update_color(self):
#########################
        self._vertex_list.colors[:] = [*self._rgb, int(self._opacity)] * self._segments * 2
#########################

window = pyglet.window.Window()
a = Arc(100, 100, 30, angle = math.pi/2)
b = Arc(100, 200, 30, angle = math.pi)
c = Arc(100, 300, 30, angle = 3*math.pi/2)

@window.event
def on_draw():
    a._vertex_list.draw(GL_LINES)
    b._vertex_list.draw(GL_LINES)
    c._vertex_list.draw(GL_LINES)

pyglet.app.run()

**Comment by nbroderick-code** [comment]
Oooh, boy! Getting excited to get me some standardized shapes!

**Comment by benmoran56** [comment]
Thanks for your feedback, and thanks @agricolab and @kcmw3e for your example code. @einarf I'll have a look at that closer for 2.0 once we can move the math into shaders. Thanks!  

I've pushed this to the 1.5-maintenance branch, and it will be in the upcoming 1.5.4 release. The Arc and Circle classes still aren't "finalized". The Circle is just a simple Circle, and the Arc is a Line based, *closed* arc.  If anyone wants to try the code, you can checkout the 1.5-maintenance branch, or update directly via pip if you have git installed: 
```pip install --upgrade --user git+https://github.com/pyglet/pyglet@pyglet-1.5-maintenance```

**Comment by benmoran56** [comment]
The shapes module is available in the latest release (v1.5.4). It's fairly limited, but I don't have the time at the moment to work on it further. If anyone has a specific shape they are interested to see happen, I'm happy to work with you on it.

**Comment by nbroderick-code** [comment]
Alright! Looking nice! This module is awesome! Basic stuff made basic. I love it.

One note: 

The example program from the module says
```
from pyglet.graphics import shapes 
```

but that didn't work for me. Instead, I had to do

```
from pyglet import shapes
```

Thanks again for all your work and taking my feedback!

**Comment by nbroderick-code** [comment]
As a user, the only thing I saw was missing was the a setter for the radius of the circle. In general, I think it's important to make the shape's parameters changeable after creation. In a game, imagine a circle that gets smaller as you run out of time.

But perhaps that's already possible and I just need docs to better understand how to use this tool.

**Comment by nbroderick-code** [comment]
Additionally, opacity does not work if you use the draw() function instead of a batch.

I know batch is more efficient, but both should function. See below test program to reproduce behavior

```

import pyglet
# from pyglet.graphics import shapes
from pyglet import shapes, clock

window = pyglet.window.Window(960, 540)
# batch = pyglet.graphics.Batch()
batch = None

circle = shapes.Circle(700, 150, 100, color=(50, 225, 30), batch=batch)
square = shapes.Rectangle(200, 200, 200, 200, color=(55, 55, 255), batch=batch)
rectangle = shapes.Rectangle(250, 300, 400, 200, color=(255, 22, 20),
                             batch=batch)
rectangle.opacity = 128
rectangle.rotation = 33
line = shapes.Line(100, 100, 100, 200, width=19, batch=batch)
line2 = shapes.Line(150, 150, 444, 111, width=4, color=(200, 20, 20),
                    batch=batch)

def grow_circle(dt):
    circle._radius += 1
    circle._update_position()

def grow_rectangle(dt):
    rectangle.width += 1

clock.schedule_interval(grow_circle, 1/30)
clock.schedule_interval(grow_rectangle, 1/30)

@window.event
def on_draw():
    window.clear()
    # batch.draw()
    circle.draw()
    square.draw()
    rectangle.draw()
    line.draw()
    line2.draw()


pyglet.app.run()
```

**Comment by caffeinepills** [comment]
Opacity is the result of blending being enabled, when used in batches this is automatically enabled through groups. When you don't use batching, there are no groups.

You will have to add:
```glEnable(GL_BLEND)
glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA)
```

This is consistent with sprites and images.

**Comment by nbroderick-code** [comment]
Ah, interesting. Okay, so that one is not a bug!

**Comment by benmoran56** [comment]
Thanks for the feedback @nbroderick-code I fixed that docstring typo. I also added the radius property so that it can be changed. I intended to have this but just forgot.

About the blending, Caffeinpills is correct. However, it turns out that all of the Shapes do have an internal group/batch even if you don't explicitly use one. Because of that I was able to update the draw method to enable blending. 
That said, you really don't want to use `Shape.draw()` methods unless you're only doing a handful of draws. If you want a way to programatically draw specific things each frame, you can put everything in a Batch and just use the `Shape.visible` boolean to "turn off" shapes that you might not want to draw each frame.

**Comment by benmoran56** [comment]
I'm going to close this now that the few bugs that popped up have gotten addressed. If anyone wants to propose another Shape, or feel free to reopen this or make a new ticket. Thanks for the feedback everyone!
