### ISSUE TITLE
Fullscreen doesn't work correctly with astraea example

### ISSUE THREAD

**Issue by vxgmichel** [pyglet/pyglet#181]
I wanted to try pyglet but it seems like the full screen mode has some issues, at least with my current configuration:
- Linux Mint 19.3 Cinnamon (x11)
- Latest commit on the `pyglet-1.5-maintenance` branch (3bdaa237c0b60371c9326762daedcd6584f3bbc0)

Here's what I get after switching the astraea game example into full screen mode:
![Screenshot from 2020-04-07 12-09-13](https://user-images.githubusercontent.com/7490006/78657261-cad57300-78c8-11ea-9706-a7c5f16db158.png)

**Comment by benmoran56** [comment]
Hi, could you tell me what desktop environment this is with? 
Also, are you using Wayland? 

I'm not able to replicate it on my local machine (Arch, vanilla Gnome).

**Comment by vxgmichel** [comment]
> Hi, could you tell me what desktop environment this is with?

Sure, I'm using Cinnamon.

> Also, are you using Wayland?

No, I'm running X11.

> I'm not able to replicate it on my local machine (Arch, vanilla Gnome).

Thanks for taking the time to try to replicate :)

**Comment by benmoran56** [comment]
I ran Astraea a few times and I **did** see this happen, but only the first time it ran. None of my subsequent runs exhibited the issue. Does this happen if you run it more than once on your machine? I might have an idea which could help but I can't really test it since I only saw it happen once in ~20 runs.

**Comment by vxgmichel** [comment]
> Does this happen if you run it more than once on your machine? 

I've tried that about 10 times on my machine and the problem occurred for each single try.

**Comment by benmoran56** [comment]
It's looking like the Astraea example will be retired, since it's quite full of legacy OpenGL code. It wouldn't be practical to update it for pyglet 2.0 (and modern OpenGL), and also it's lacking external documentation. Instead, the much more simplistic `example/game` should be considered it's replacement. It's not as fleshed out, but it's better suited as an example due to it's tutorial in the pyglet documentation. 

Sorry for leaving this hanging so long!
