### ISSUE TITLE
pyglet.media.exceptions.MediaException: Unsupported sample size

### ISSUE THREAD

**Issue by xantares** [pyglet/pyglet#191]
pyglet>=1.5.1 (including latest) has trouble playing some music:
```
import pyglet
player = pyglet.media.Player()
sound = pyglet.media.load('Concert.ogg')
player.queue(sound)
player.play()
```
(use https://github.com/samcv/brainworkshop/blob/master/res/music/advance/Concert.ogg)

fails with:
```
Traceback (most recent call last):
  File "/home/xantares/.local/lib/python3.8/site-packages/pyglet/media/drivers/openal/interface.py", line 474, in data
    al_format = self._format_map[(audio_format.channels, audio_format.sample_size)]
KeyError: (2, 32)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bug_channels.py", line 7, in <module>
    player.play()
  File "/home/xantares/.local/lib/python3.8/site-packages/pyglet/media/player.py", line 248, in play
    self._set_playing(True)
  File "/home/xantares/.local/lib/python3.8/site-packages/pyglet/media/player.py", line 198, in _set_playing
    self._create_audio_player()
  File "/home/xantares/.local/lib/python3.8/site-packages/pyglet/media/player.py", line 364, in _create_audio_player
    self._audio_player = audio_driver.create_audio_player(source, self)
  File "/home/xantares/.local/lib/python3.8/site-packages/pyglet/media/drivers/openal/adaptation.py", line 66, in create_audio_player
    return OpenALAudioPlayer(self, source, player)
  File "/home/xantares/.local/lib/python3.8/site-packages/pyglet/media/drivers/openal/adaptation.py", line 163, in __init__
    self.refill(self.ideal_buffer_size)
  File "/home/xantares/.local/lib/python3.8/site-packages/pyglet/media/drivers/openal/adaptation.py", line 291, in refill
    self._queue_audio_data(audio_data, length)
  File "/home/xantares/.local/lib/python3.8/site-packages/pyglet/media/drivers/openal/adaptation.py", line 321, in _queue_audio_data
    buf.data(audio_data, self.source.audio_format, length)
  File "/home/xantares/.local/lib/python3.8/site-packages/pyglet/media/drivers/openal/interface.py", line 476, in data
    raise MediaException('Unsupported sample size')
pyglet.media.exceptions.MediaException: Unsupported sample size
```

the difference is that audio_format.channels=2 with pyglet>=1.5.1 
```
try:
         al_format = self._format_map[(audio_format.channels, audio_format.sample_size)]
     except KeyError:
          raise MediaException('Unsupported sample size')
```

but the `_format_map` is `{(1, 8): 4352, (1, 16): 4353, (2, 8): 4354, (2, 16): 4355}`

**Comment by xantares** [comment]
maybe somehow related https://github.com/pyglet/pyglet/commit/7806afcbcd048b3756d08cdea3932b8177e69566 (although this commit is much older)

cc @dangillet

**Comment by benmoran56** [comment]
Thanks for opening the ticket. 

The exception is correct, that 32bit sample size audio is not supported by the OpenAL backend. It seems that on Linux (maybe every platform?) that OpenAL can only handle 8bit and 16bit.

The PulseAudio backend could be updated to handle 32bit, but that backend does have some stability issues with playback of many short samples. PulseAudio backend is also limited in that it doesn't support spatial audio.  In any case, i'll have a look at that and see if can be done.

**Comment by xantares** [comment]
by curiosity, do you know which commit/PR in pyglet is responsible for the increased sample size ?

**Comment by xantares** [comment]
how do we choose which decoder backed is used by default, is it alwayes gstreamer now ?

**Comment by benmoran56** [comment]
The minimal script won't play anything unless you enter into the event loop `pyglet.app.run()`. 
The way to manually choose the decoder backend is just as I posted above, otherwise it just tries them in order of the formats they support. 

After some thought, I decided to change the GStreamer decoder to clamp to 16bit. This means it will downsample sources like "Concert.ogg" to 16bit, even though it's a 32bit source. Since the audio backends don't support anything higher, this is better than crashing. 

The change will be in the next point release. In the meantime, you can update to the latest version with: ```pip install --user git+https://github.com/pyglet/pyglet@pyglet-1.5-maintenance```

**Comment by xantares** [comment]
thanks!

**Comment by benmoran56** [comment]
There are a few small issues in your example that are preventing it from playing. A small one is that you're scheduling the audio_callback class repeatedly, which would keep playing or queuing the same song over and over. You can `schedule_once` instead: 
```
pyglet.clock.schedule_once(audio_callback, 2.0)
```

In the audio_callback class, the `if 1:` case won't work because the `player` instance is getting garbage collected when the function finishes. You will need to make a permanent reference to the `player` instance, somewhere outside of the function, to keep it around. 
The `else:` case in audio_callback actually would have worked if it was reachable, because calling `.play()` directly on an audio Source creates an internal, temporary Player instance, which gets cleaned up automatically when the Source is finished playing. 

So this would work: 
```
# Player that won't get garbage collected:
player = pyglet.media.Player()

def audio_callback(dt):
    print('-- audio_callback')
    f = 'Concert.ogg'
    sound = pyglet.resource.media(f)
    player.queue(sound)
    player.play()
```

Or this, for a temporary Player:
```py
def audio_callback(dt):
    print('-- audio_callback')
    f = 'Concert.ogg'
    music = pyglet.resource.media(f)
    music.play()
```

**Comment by xantares** [comment]
ok, I see, thanks for pointing that out

**Comment by benmoran56** [comment]
I'll close this for now, but please feel free to comment, or reopen it if you still have issues.  Also, feel free to join the Discord server (the link is in the README, or pyglet.org). Thanks!
