### ISSUE TITLE
on_mouse_scroll returns 0 for small scrolls on macOS

### ISSUE THREAD

**Issue by eterevsky** [pyglet/pyglet#193]
On macOS for small (one-click) scrolls with a mouse or with the trackpad `on_mouse_scroll` event receives 0 as `scroll_y`. Example code:

```python
import pyglet
window = pyglet.window.Window()

@window.event
def on_mouse_scroll(x, y, scroll_x, scroll_y):
    print('on_mouse_scroll', x, y, scroll_x, scroll_y)

pyglet.app.run()
```

When trying to scroll slowly inside the window, both `scroll_x` and `scroll_y` are 0. For faster scrolls some non-zero values are passed.

The documentation states that `scroll_x` and `scroll_y` parameters are supposed to be integer, so it's possible that the system provides a non-zero floating point value, which is then rounded to an integer.

Machine: Macbook Pro + internal trackpad or external Razer mouse
System: macOS Catalina 10.15.4
Python 3.8
Pyglet 1.5.5

**Comment by benmoran56** [comment]
I had a look at this, and it's clamping to the nearest int and losing the fractional values. 
At the top of `pyglet/window/cocoa/pyglet_view.py` you can see the following function:
```py
def getMouseDelta(nsevent):
    dx = nsevent.deltaX()
    dy = -nsevent.deltaY()
    return int(round(dx)), int(round(dy))
```
In the past, it made sense to return ints, but I don't see any reason for it now. Especially since pyglet 1.5+ is Python 3 only, there are no more int/float conflicts to worry about. 

If possible, could you try modifying that function and seeing if it does the trick?

**Comment by benmoran56** [comment]
Just to add, it turns out we've been returning floats on Windows already, so it should be fine to switch to floats.

**Comment by benmoran56** [comment]
This is merged in for the next release, so I'll close this for now. Thanks again!
