### ISSUE TITLE
Feature Request: More MouseStateHandler events.

### ISSUE THREAD

**Issue by DoAltPlusF4** [pyglet/pyglet#195]
I think the `pyglet.window.key.KeyStateHandler` and `pyglet.window.mouse.MouseStateHandler` classes are both very useful, but I think the `MouseStateHandler` could be allot more useful if it included more of the mouse events, such as `on_mouse_motion` and `on_mouse_scroll`.

# on_mouse_motion
```py
def on_mouse_motion(self, x, y, dx, dy):
    self["x"] = x
    self["y"] = y
    self["dx"] = dx
    self["dy"] = dy
```

# on_mouse_scroll
```py
def on_mouse_scroll(self, x, y, scroll_x, scroll_y):
    self["scroll_x"] = scroll_x
    self["scroll_y"] = scroll_y
```

# __init__ method
Due to the new values, an `__init__` method will be required in order to avoid receiving `False` if the value is not found. (Ideally `0` should be returned if `x`, `y`, `dx`, `dy`, `scroll_x` or `scroll_y` are not found.)
```py
def __init__(self):
        self["x"] = 0
        self["y"] = 0
        self["dx"] = 0
        self["dy"] = 0
        self["scroll_x"] = 0
        self["scroll_y"] = 0
```

The new `MouseStateHandler` class should look like this now:
```py
class MouseStateHandler(dict):
    """Simple handler that tracks the state of buttons from the mouse. If a
    button is pressed then this handler holds a True value for it.

    For example::

        >>> win = window.Window
        >>> mousebuttons = mouse.MouseStateHandler()
        >>> win.push_handlers(mousebuttons)

        # Hold down the "left" button...

        >>> mousebuttons[mouse.LEFT]
        True
        >>> mousebuttons[mouse.RIGHT]
        False

    """

    def __init__(self):
        self["x"] = 0  # To avoid the user recieving `False` if the key is not found
        self["y"] = 0
        self["dx"] = 0
        self["dy"] = 0
        self["scroll_x"] = 0
        self["scroll_y"] = 0

    def on_mouse_press(self, x, y, button, modifiers):
        self[button] = True

    def on_mouse_release(self, x, y, button, modifiers):
        self[button] = False

    def on_mouse_motion(self, x, y, dx, dy):
        self["x"] = x
        self["y"] = y
        self["dx"] = dx
        self["dy"] = dy

    def on_mouse_scroll(self, x, y, scroll_x, scroll_y):
        self["scroll_x"] = scroll_x
        self["scroll_y"] = scroll_y

    def __getitem__(self, key):
        return self.get(key, False)
```

**Comment by DoAltPlusF4** [comment]
BTW, this is my first time making one of these, should I be making a PR for this?

**Comment by benmoran56** [comment]
Hi, thanks for opening the ticket. 

This looks good, but the only concern I would have is that the motion based events will always contain the last value. Unlike the button presses, they will never reset to 0, so it might cause confusion if you're trying to poll the state every frame. What do you think? 

Oh, and as for the workflow, for new ideas it's usually a good idea to open a ticket like this to get feedback first. If things are agreed upon, then you can follow up with a PR that contains the work. This is also a good idea if you want to make a big change, because it can be frustrating to put a lot of work into something and hit a block later. This is good general advice for contributing to most projects I think.

**Comment by caffeinepills** [comment]
In my opinion, this kind of falls outside the purpose of a state handler. The handler is to tell what state something is currently at. Mouse scroll won't tell you if it's scrolling, since it never resets. I personally wouldn't really count positions as a state either in this context. At that point it just becomes a container for all of the event data, which generally should be implemented by the application.

**Comment by DoAltPlusF4** [comment]
> This looks good, but the only concern I would have is that the motion based events will always contain the last value. Unlike the button presses, they will never reset to 0, so it might cause confusion if you're trying to poll the state every frame. What do you think?

I think I overlooked this, yeah. Do you have any ideas on how to reset the values to zero every tick?  I don't really want to schedule anything but we might have to for performance reasons.

> Oh, and as for the workflow, for new ideas it's usually a good idea to open a ticket like this to get feedback first. If things are agreed upon, then you can follow up with a PR that contains the work. This is also a good idea if you want to make a big change, because it can be frustrating to put a lot of work into something and hit a block later. This is good general advice for contributing to most projects I think.
Good to know, thanks :)

**Comment by DoAltPlusF4** [comment]
> In my opinion, this kind of falls outside the purpose of a state handler. The handler is to tell what state something is currently at. Mouse scroll won't tell you if it's scrolling, since it never resets. I personally wouldn't really count positions as a state either in this context. At that point it just becomes a container for all of the event data, which generally should be implemented by the application.

I would say that the mouse's position would count as part of it's "state". One example of where this might be useful could be for if the user wanted to make a fully automatic weapon in a shooter game, they would not be able to use `on_mouse_press` as that would only be called once, so the code would need to go in the update function. To retrieve the mouse position they would need to have something that logs the mouse's position every time it moves, so why not make the `MouseStateHandler` do that? The position would not be hard to implement, and it is still just changing values during events, just like the button values.

**Comment by benmoran56** [comment]
The delta positions can't really be done accurately for all cases. Polling (scheduing something) won't work reliably, since pointing devices have wildly varying update frequencies. This means that the updates fall in between frames, so you either have to overwrite or add previous values. Then when read, you would have to do something like manually reset the values back to zero. 

A one-size fits all solution would be very difficult. This is really the type of thing that event driven programming is perfect for. For something like a camera, you would have your own specific way of storing the state (either overwriting the previous values, for for things like scrolling, or adding the previous values for things like movement). You would update that object with your own custom event handlers, and be able to choose how to handle the exact case with regards to updating/replacing existing values.

**Comment by DoAltPlusF4** [comment]
Anyway, even if the delta positions can't be added, I still think that the X and Y position values should be implemented. I don't see there being any problems with adding these, and I think they do count as part of the mouses state.

**Comment by benmoran56** [comment]
That sounds reasonable. Do you want to make a pull request for that?

**Comment by DoAltPlusF4** [comment]
Sure, one minute.

**Comment by benmoran56** [comment]
Thanks, merged that in.
