### ISSUE TITLE
Batch does not display

### ISSUE THREAD

**Issue by Kalin-Rudnicki** [pyglet/pyglet#251]
I am trying to display 3 100x100 grids, with either red or green rectangles. Something along the lines of:

```python
for i in range(0, 3):
    for y in range(0, 100):
         for x in range(0, 100):
            Rectangle(stuff).draw()
```
When I do it is this way, it is very laggy, but it least it eventually ends up displaying.
When I try and do something along the lines of:

```python
batch = Batch()
for i in range(0, 3):
    for y in range(0, 100):
         for x in range(0, 100):
            Rectangle(stuff, batch=batch)
batch.draw()
```
then nothing shows up, even after waiting.  
Am I doing something wrong, or is something not working?

**Comment by benmoran56** [comment]
The issue is likely that your `Rectangle` objects are being garbage collected as soon as they're made. When this happens they are removed from the batch. All you should need to do is keep a reference to them somewhere: 
```py
shapes = []
...
rect = Rectangle(.....)
shapes.append(rect)
...
```
In the first example they are also being garbage collected, but you're drawing them first before that happens. As you said though, it will be very slow to individually draw objects like this. You definitely do want to use Batches for performance reasons.

**Comment by Kalin-Rudnicki** [comment]
It works perfect :)
And is WAY faster, thanks a bunch!

**Comment by benmoran56** [comment]
Great!
