### ISSUE TITLE
Proposed New Wiki 

### ISSUE THREAD

**Issue by Bervenia** [pyglet/pyglet#254]
Hello,

I've recently forked and updated the wiki to be more up to date. Unfortunately GitHub does not support pull requests for the wiki, so here is a link to [my version](https://github.com/Bervenia/pyglet).  I've made a handful of changes that I believe will help flesh out the wiki a little more.  I'll detail some of the changes I've made below and am open to any feedback. 

Thank you.

#### Changes Include:
* Capitalization
* Additional links like to examples
* Consistent header and footer 
* Simple window tutorial on home page
* Removal of docs page in place of direct link to read the docs 
* Combined ideas page with contributing 
* Removed Pyglet 1.4 from roadmap due to all elements being complete

**Comment by benmoran56** [comment]
First of all, my apologies that this ticket went unanswered, and that so much time has past. 

Since you've opened it, a decision was made to remove the wiki altogether. It turned that hardly anyone was visiting it. Instead, most of the general information should be replicated at the top of the README. As for the roadmap, that is succeeded by the "projects" tab on GitHub.

If you have any suggestions to improve any of that, please do let us know!
