### ISSUE TITLE
pyglet.text.formats.attributed will break in Python 3.10

### ISSUE THREAD

**Issue by encukou** [pyglet/pyglet#312]
Python 3.10 will [remove the `parser` module](https://docs.python.org/3/library/parser.html) after Python 3.9 switched to a different, more powerful PEG parser.

The `parser` module is currently used in `pyglet.text.formats.attributed` to evaluate and validate attributes, so in py3.10 `import pyglet` itself fails with ImportError.

I'd like to fix this, but I couldn't find docs, tests or examples for code evaluation in attributed text. What exactly is it supposed to do?
Would [`ast.literal_eval`](https://docs.python.org/3.8/library/ast.html#ast.literal_eval) work here? It can parse basic Python objects (strings, numbers, tuples, dicts, booleans, etc.), but unlike existing AttributedTextDecoder, it doesn't allow expressions like `3+4`. Is support for such expressions intended?

One reason I'd prefer switching to `ast.literal_eval` is that that the current is quite quirky: decoding attributes can raise `TypeError` (`2+"x"`) or ZeroDivisionError (`2/0`), but e.g. `True and False` is not supported. Emulating these details with a different parser would be hard.
I also see that attributed text just accidentally avoided a security issue when f-strings were added to Python. Text attributes and f-strings happen to use the same delimiters, `{}`; if they didn't, attributed text would allow arbitrary code execution. Other security issues might be introduced in new Python versions, or might already be there. The `ast_literal_eval` function, on the other hand, will be kept safe.

**Comment by benmoran56** [comment]
Thanks for opening the ticket, and for the heads up.

It looks like `parser` can indeed be easily replaced by `ast.literal_eval`, so I just went ahead and did that. 
I was also able to remove the custom safety checking code, since this should be handled automatically
now.  If you want to check out the code, it will be in the `pyglet-1.5-maintenance` branch. 
If you also have any other comments or suggestions with regards to evaling the code, that would be 
appreciated. I think it should be OK, but I'm not an expert. 

You can read about the pyglet `attributed` text decoding here: 
https://pyglet.readthedocs.io/en/latest/programming_guide/text.html#attributed-text

And a short example of how it works in practice: 
```py
import pyglet


window = pyglet.window.Window()


raw_text = "{font_name 'Times New Roman'}{font_size 28}{color (255, 255, 0, 255)}Hello{font_size 12}, " \
           "{color (255, 0, 0, 255)}world{color (0, 0, 0, 255)}!"

doc = pyglet.text.decode_attributed(raw_text)
layout = pyglet.text.layout.TextLayout(document=doc)
layout.x = 100
layout.y = 200


@window.event
def on_draw():
    window.clear()
    layout.draw()


pyglet.app.run()
```
There are also unit tests:
```
pytest tests/unit/test_text.py
pytest tests/interactive/text/
```

**Comment by encukou** [comment]
Alright, ast_eval` should suffice then. Previously, you could do things like `"{font_size 3*12}Hello"`; I hope no one noticed this possibility.

Thank you!

Other usages of `eval` are in `tools/wraptypes`. Seems like both can be replaced with `ast_literal_eval`, but the tool looks like it operates on fixed input.
