### ISSUE TITLE
TypeError with clock.schedule_interval

### ISSUE THREAD

**Issue by mjohnson-fr** [pyglet/pyglet#329]
Hi, I adapted a program to display animated GIFs in the current directory, with a keypress making the program load a new random image. This works fine until I add a clock.schedule_interval event, whereupon I get a TypeError saying my update_image function takes 0 positional arguments but 1 was given. I didn't give any arguments knowingly. Thanks for any help! 
[x.zip](https://github.com/pyglet/pyglet/files/5683528/x.zip)
I'm using python3 on a Raspberry Pi.

**Comment by LennyPhoenix** [comment]
If you are scheduling the `update_image` function, it needs to take a `dt: float` argument. 

You can fix this easily by changing line 9 to the following:
```py
def update_image(dt = None):
```
(Defaulting it to `None` allows you to call manually too.)

The `dt` argument is set to the time passed since the last call, which can be used to make frame independent changes. (Not necessary here, but you still need to add the argument.)

**Comment by mjohnson-fr** [comment]
Thank you !
