### ISSUE TITLE
Unexpected(?) behavior with EventDispatcher and garbage collection

### ISSUE THREAD

**Issue by ScottDDexter** [pyglet/pyglet#365]
It's more likely this is an issue with my expectations, or possibly the documentation, rather than the code, but:

I'm teaching pyglet, starting with the asteroids clone at https://github.com/pyglet/pyglet/tree/master/examples/game (which is an excellent teaching tool). My understanding is that the `EventDispatcher` uses weak references so as not to get in the way of garbage collection. But that doesn't _appear_ to be working properly:

 In both versions 4 and 5 of the asteroids clone (where collision detection and handling are implemented), when `player_ship.delete()` is invoked,  the ship object's resources are gc'd, but (unexpectedly) the `player_ship` object itself is not. So, if you then press the space bar (to `fire()` a bullet), you get an exception arising from the ship's `on_key_press` handler (which shouldn't exist?) complaining that the ship's image-object no longer exists. (traceback below).

But I would _expect_ that event handlers belonging to objects I deleted would vanish from the event handler stack. 

I will be grateful for any clarification on how I should be thinking about this!

Running pyglet 1.5.15, python 3.9.1, pycharm CE 2020.3.4.

```
Traceback (most recent call last):
  File "<snip>/PyCharmProjects/csc121setup/venv/lib/python3.9/site-packages/pyglet/libs/darwin/cocoapy/runtime.py", line 1141, in objc_method
    result = f(py_self, *args)
  File "<snip>/PyCharmProjects/csc121setup/venv/lib/python3.9/site-packages/pyglet/window/cocoa/pyglet_view.py", line 199, in pygletKeyDown_
    self._window.dispatch_event('on_key_press', symbol, modifiers)
  File "<snip>/PyCharmProjects/csc121setup/venv/lib/python3.9/site-packages/pyglet/window/__init__.py", line 1333, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "<snip>/PyCharmProjects/csc121setup/venv/lib/python3.9/site-packages/pyglet/event.py", line 408, in dispatch_event
    if handler(*args):
  File "<snip>/PyCharmProjects/pygletIntro/src/version5/game/player.py", line 56, in on_key_press
    self.fire()
  File "<snip>/PyCharmProjects/pygletIntro/src/version5/game/player.py", line 63, in fire
    ship_radius = self.image.width / 2
AttributeError: 'NoneType' object has no attribute 'width'
```

**Comment by benmoran56** [comment]
Hi Scott, my apologies for the slow response. 

One important thing to know is that the `.delete()` methods found on pyglet objects (like Sprites, Labels, Shapes), only do one thing: they ensure that the object's resources are deleted on the GPU side.  Calling `delete()` on a Sprite will not delete the sprite instance itself, but only it's image and vertex data.  This means that the Sprite's event handlers are all still there, until you get rid of the Sprite instance itself. This can lead to the traceback above, since the Sprite's image has been wiped. 

A common pattern would be something like: 

```py
for spr in dead_sprites:
    spr.delete()

dead_sprites.clear()
```

Normally, manually calling `.delete()` is not even necessary - you can simply let the Sprite instance fall out of scope, and Python's garbage collector will clean it up when the `Sprite.__del__()` method is invoked. On CPython this occurs immediately, but other Python implementations (like PyPy) have different garbage collectors, so `__del__` is _not_ called immediately. In those cases, you would want to use the `delete()` method to ensure immediate removal from the GPU. 

I haven't looked at those two examples yet, so maybe there is a bug in there as well.

**Comment by ScottDDexter** [comment]
Thank you--this is very helpful. I'll revisit this example (and the discussion about it in the docs) and see if there's anything to be clarified, and submit a PR if so.
