### ISSUE TITLE
Replay a pyglet session

### ISSUE THREAD

**Issue by benoitvalery** [pyglet/pyglet#368]
Hi everyone,

I'm currently developing a multitasking environment with pyglet, and I have to say that I find pyglet impressive and well designed. Next step for me is to develop a Replay module so that users can load back and visualize a multitasking session. The main purpose of it being training multitasking skills.
To you, what would be the best way to "intercept" the visual environment and write it somewhere, so I can draw it back with a special scheduler.

To do so: I was thinking about recording directly vertices information that pass through the batch (I'm using a single batch, and  a single Window). Do you think I'm on the right way ? Do you have any other idea of where pyglet offers the most exhaustive amount of what is displayed, at a current time.

Thank you in advance for your responses.

**Comment by benmoran56** [comment]
This is an interesting question. Are you adding all of the objects directly to the Batch, with `Batch.add(....)`? 
If so, you can potentially just override the `Batch.add` method with a custom method. Something that will log a relative time-stamp, plus the arguments.  From the log, you should be able to "play it back" in a new session.  

Are you needing to track deleted items as well?

**Comment by benoitvalery** [comment]
Yes, I'm adding all the objects to the window's batch, but once the object is added, its values can still be modified (for example its position might change with time). Ideally, I would like to look at the batch, wait for a value (e.g., position) to change, and log any change. Don't you think that, if a customize only my batch.add, I will be informed about what is added, but not the following value changes ?

I have to say that I have other ideas to do my Replay, that would by less "overshot", but it would be great if we knew that, at least, there somewhere in the code where we can "see" the magic...

**Comment by benmoran56** [comment]
In that case it won't be quite so simple. Querying the internal state the Batch might be a bit difficult. It does a lot of internal sorting to keep things efficient. It first sorts and consolidates objects by their Group. After that, it places them into an appropriate VertexDomain - depending on the actual vertex types. The VertexDomain is what actually "owns" the buffers and allocation information. You can't easily query things at this level, since all of the data is consolidated. Instead, you need to keep track of the VertexLists (which are returned when calling `Batch.add(...)`. The VertexLists are basically the accessors to a chunk of data into the buffer.  (Sorry if this is all a bit confusing). 

If I was to do this myself, I would probably create a high level class that would own the `Batch.add(...)` operations, and wrap the returned `VertexLists` with a custom class. This would give you hooks into "recording" both the creation, deletion, and modification of everything.  Essentially, you're just recording the instructions, not the actual GPU state. 

This is all just some quick pseudocode, but maybe it will give some ideas: 

```py

class WrappedVertexList:
    def __init__(recorder, id, vertex_list):
        self._recorder = recorder
        self._id = id
        self._vlist = vertex_list

    # use properties, or __get_attr__ overrides to catch and log updates, and delete calls, etc. 

    @property
    def vertices(self)
        return self._vlist.vertices
    
    @vertices.setter
    def vertices(self, vertices):
        self._recorder.log("update_vertices", self._id,  vertices)
        self._vlist.vertices[:] = vertices


class Recorder:
    def __init__(batch):
        self._batch = batch
        self._vlist_id = 0

    def log(self):
        # log to disk

    def add(self, count, mode, group, *data)
        self.log("add", count, mode, group, data)
        vlist = self._batch.add(count, mode, group, *data)
        self._vlist_id += 1
        return WrapVertexList(self, self._vlist_id, vlist)
```

**Comment by benoitvalery** [comment]
Thanks for your explanation. The thing is quite clear to me and will help me in thinking about how to achieve this.
