### ISSUE TITLE
FPSDisplay delivers wrong values

### ISSUE THREAD

**Issue by andreaszdw** [pyglet/pyglet#37]
The values delievered by ` pyglet.window.FPSDisplay` are wrong. It looks like they depend on the value set in `update_period`, not the real fps.

This sample code

```import pyglet


class HelloWorldWindow(pyglet.window.Window):

    def __init__(self):
        super(HelloWorldWindow, self).__init__(width=800, height=600, vsync=False)
        self.fps_display = pyglet.window.FPSDisplay(self)
        self.fps_display.update_period = 0.0001
        pyglet.clock.schedule_interval(self.update, 1./60)

    def on_draw(self):
        self.clear()
        self.fps_display.draw()

    def update(self, dt):
        print(pyglet.clock.get_fps())


if __name__ == '__main__':
    window = HelloWorldWindow()
    pyglet.app.run()
```

delivers in the console for example 478.0694218152703 but in the window always 10000.00.

If I change the value in `update_period` the display in the window changes dependend on the value, not the real fps.

**Comment by benmoran56** [comment]
Looks like the calculation is slightly broken. Thanks for opening the ticket.

**Comment by benmoran56** [comment]
Looking into this further, it turns out that `clock.get_fps` has been broken for a long time. It was likely intended to work with the old `set_fps_limit` API which was long deprecated and has been removed.

The FPSDisplay issue itself is a simple 1 line fix. Fixing it, however, seems to indicate that the clock itself is slightly inaccurate (at least on Linux). This needs more investigation. 

As a quick note, setting the `FPSDisplay.update_period` to a shorter interval than the clock is being updated will result in inaccurate results.

**Comment by benmoran56** [comment]
The FPSDisplay should now be fixed in master. Please note that if you set the `FPSDisplay.update_period` to a value that is less than the Window refresh speed, it will give inaccurate results. I have updated the docstrings to explain this as well. 

For the `clock.get_fps`, it turns out that it's not broken at all. Instead, the name is just confusing. This value indicates how many times the internal clock is refreshing. This value will change depending on how many Platform events exist, such as mouse movement, keyboard input, etc. It is **not** an indicator of screen refresh speed. I have updated the docstrings to explain this as well.

**Comment by benmoran56** [comment]
Please reopen this if you have any additional comments or issues. Thanks!
