### ISSUE TITLE
Texts are not displayed correctly

### ISSUE THREAD

**Issue by Jalkhov** [pyglet/pyglet#374]
I don't know if it's a problem with my computer, because of opengl or something like that, but I'm following [this tutorial](https://pyglet.readthedocs.io/en/latest/programming_guide/examplegame.html#programming-guide-game) to the letter and the texts are displayed like this, everything looks fine, except the texts (labels), what can it be?
![pyglet_issue](https://user-images.githubusercontent.com/36505934/114954515-c40d0480-9e28-11eb-9f20-45fc4249828e.png)

**Comment by benmoran56** [comment]
Are you using older Intel graphics, with Windows 10?

**Comment by Jalkhov** [comment]
> Are you using older Intel graphics, with Windows 10?

I wouldn't know, I have updated drivers, but yes, my processor is intel and I have windows 10 ltsc.

**Comment by pushfoo** [comment]
@Jalkhov 
1. type `dxdiag` into the windows search bar (or hit `windows key + r` to bring up the run prompt and type `dxdiag` there)
2. press enter
3. Open the display tab at the top, like in the image below.
![image](https://user-images.githubusercontent.com/36696816/114979393-ce46f700-9e58-11eb-80cc-3b7196d3600a.png)
4. Please post a screenshot of what you see.

With the GPU shortage looking like it will go on for a while, finding solutions or workarounds for graphics issues on budget and integrated graphics cards will be important.

**Comment by Jalkhov** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/36505934/115015360-84263b80-9e81-11eb-8258-a4e3b7aec3ed.png)

**Comment by benmoran56** [comment]
Could you also paste the output of `Python -m pyglet.info` on the CLI? 
Or, from a script: 
```py
import pyglet.info
print(pyglet.info.dump())
```

**Comment by Jalkhov** [comment]
Platform
------------------------------------------------------------------------------
platform:  Windows-10-10.0.17763-SP0
release:   10
machine:   AMD64

Python
------------------------------------------------------------------------------
implementation: CPython
sys.version: 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)]
sys.maxint: 9223372036854775807
os.getcwd(): C:\Users\myuser\folder\folder1\Python\Pyglet\game\version0.1

pyglet
------------------------------------------------------------------------------
pyglet.version: 1.5.16
pyglet.compat_platform: win32
pyglet.__file__: C:\Users\myuser\pyglet\lib\site-packages\pyglet\__init__.py
pyglet.options['audio'] = ('xaudio2', 'directsound', 'openal', 'pulse', 'silent')
pyglet.options['debug_font'] = False
pyglet.options['debug_gl'] = True
pyglet.options['debug_gl_trace'] = False
pyglet.options['debug_gl_trace_args'] = False
pyglet.options['debug_graphics_batch'] = False
pyglet.options['debug_lib'] = False
pyglet.options['debug_media'] = False
pyglet.options['debug_texture'] = False
pyglet.options['debug_trace'] = False
pyglet.options['debug_trace_args'] = False
pyglet.options['debug_trace_depth'] = 1
pyglet.options['debug_trace_flush'] = True
pyglet.options['debug_win32'] = False
pyglet.options['debug_x11'] = False
pyglet.options['graphics_vbo'] = True
pyglet.options['shadow_window'] = True
pyglet.options['vsync'] = None
pyglet.options['xsync'] = True
pyglet.options['xlib_fullscreen_override_redirect'] = False
pyglet.options['darwin_cocoa'] = True
pyglet.options['search_local_libs'] = True
pyglet.options['advanced_font_features'] = False
pyglet.options['headless'] = False
pyglet.options['headless_device'] = 0

pyglet.window
------------------------------------------------------------------------------
display: <pyglet.canvas.win32.Win32Display object at 0x0000026BAB9B5BE0>
screens[0]: Win32Screen(x=0, y=0, width=1152, height=864)
config['double_buffer'] = True
config['stereo'] = False
config['buffer_size'] = 32
config['aux_buffers'] = 0
config['sample_buffers'] = 0
config['samples'] = 0
config['red_size'] = 8
config['green_size'] = 8
config['blue_size'] = 8
config['alpha_size'] = 0
config['depth_size'] = 32
config['stencil_size'] = 8
config['accum_red_size'] = 16
config['accum_green_size'] = 16
config['accum_blue_size'] = 16
config['accum_alpha_size'] = 0
config['major_version'] = None
config['minor_version'] = None
config['forward_compatible'] = None
config['debug'] = None
context: Win32Context()

window.context._info
------------------------------------------------------------------------------
gl_info.get_version(): 1.1.0
gl_info.get_vendor(): Microsoft Corporation
gl_info.get_renderer(): GDI Generic
gl_info.get_extensions():
   GL_EXT_bgra
   GL_EXT_paletted_texture
   GL_WIN_swap_hint

pyglet.gl.glu_info
------------------------------------------------------------------------------
glu_info.get_version(): 1.2.2.0 Microsoft Corporation
glu_info.get_extensions():
   GL_EXT_bgra

pyglet.gl.glx_info
------------------------------------------------------------------------------
GLX not available.

pyglet.media
------------------------------------------------------------------------------
audio driver: <pyglet.media.drivers.directsound.adaptation.DirectSoundDriver object at 0x0000026BAB51DEE0>

pyglet.media.ffmpeg
------------------------------------------------------------------------------
FFmpeg not available.

pyglet.media.drivers.openal
------------------------------------------------------------------------------
Library: <CDLL 'openal32', handle 10000000 at 0x26baeb194f0>
Version: 1.1
Extensions:
   ALC_ENUMERATE_ALL_EXT
   ALC_ENUMERATION_EXT
   ALC_EXT_CAPTURE
   ALC_EXT_EFX

pyglet.input.wintab
------------------------------------------------------------------------------
WinTab not available.
None

**Comment by benmoran56** [comment]
Thanks @Jalkhov.  It seems like it's an OpenGL issue.
The "Microsoft Corporation GDI Generic" is a fallback driver, and won't 
provide full OpenGL support. If possible, see if you can download the
latest drivers from Intel. 

```py
gl_info.get_version(): 1.1.0
gl_info.get_vendor(): Microsoft Corporation
gl_info.get_renderer(): GDI Generic

pyglet.gl.glu_info
glu_info.get_version(): 1.2.2.0 Microsoft Corporation
```

**Comment by pushfoo** [comment]
@Jalkhov I think you might be misunderstanding. How and from where are you trying to find updated drivers?

As far as I know, a generic GDI driver is what Windows uses when there is no actual driver installed for the GPU. If windows isn't automatically installing a driver, you may be able to download it from the manufacturer website instead. 

[Intel lists their driver downloads on their site](https://downloadcenter.intel.com/product/80939/Graphics). If you give us a screenshot of the processor entry on the System tab in dxdiag, the same utility I asked you to screenshot earlier, we can help you choose the appropriate driver to install.

**Comment by Jalkhov** [comment]
Ah ok, I have run the Driver Booster on the computer and there is nothing to update. Here is the screenshot.
![Screenshot_2](https://user-images.githubusercontent.com/36505934/115037018-07ed2180-9e9c-11eb-9aef-e5993e4f2ef0.png)

**Comment by pushfoo** [comment]
Thank you. I think I found a driver that might work. Although it is originally for Windows 8.1, it may work on Windows 10. Try the following steps:
1. Go to [the graphics driver page for your generation of processor](https://downloadcenter.intel.com/download/24970/Intel-Graphics-Driver-for-Windows-15-28-).
2. Download the installer for the latest Windows 8.1 driver for your GPU. It is the top entry on the lefthand side under "Available Downloads", and is labelled `win64_152824.exe`:
![image](https://user-images.githubusercontent.com/36696816/115040793-c9f1fc80-9e9f-11eb-813f-d126447fb22f.png)

2. Run the installation.
3. If you encounter any errors, post screenshots here.
3. If the install works without any errors, fully shutdown your system, then turn it back on.
4. Check if pyglet draws text correctly.
5. Let us know what happened, and paste the results of pyglet diagnostics (`python -m pyglet.info`)
 again.

If the steps above don't change anything, there are still a few more things we can try.

**Comment by Jalkhov** [comment]
@pushfoo I'm getting the following warning, it says that the drivers I have installed are newer than the ones I'm trying to install, I'm still trying to install?
![Screenshot_3](https://user-images.githubusercontent.com/36505934/115047385-7636e180-9ea6-11eb-88a8-849fc45a475d.png)

**Comment by pushfoo** [comment]
That's unexpected. I thought there wouldn't be any drivers listed. I'm not sure why it's using GDI drivers if you have other drivers installed. Do you know if you might somehow be using another GPU that doesn't have drivers for it? Try going into device manager and look under Display Adapters. What's listed there? Also. if your computer is a desktop, check whether you have the video cable plugged into a port on a card slot rather than the built-in ports for the motherboard.

**Comment by Jalkhov** [comment]
This is what appears in the Device Manager:

![Screenshot_4](https://user-images.githubusercontent.com/36505934/115050065-5fde5500-9ea9-11eb-9f17-8589b96b7db9.png)

My computer is a Laptop with a monitor connected by VGA.

**Comment by pushfoo** [comment]
1. Double click Intel (R) HD Graphics
2. In the window that pops up, go to the Driver tab
3. What shoes up there?
4. What shows up under driver details?
Also, have you tried restarting your computer?

**Comment by Jalkhov** [comment]
![Screenshot_5](https://user-images.githubusercontent.com/36505934/115051322-b009e700-9eaa-11eb-9ae9-fdfc80540dfe.png)
![Screenshot_6](https://user-images.githubusercontent.com/36505934/115051329-b26c4100-9eaa-11eb-812e-ab1de5b1662b.png)

Well, I asked the question yesterday, I turned the computer off and on, but everything is still the same.

**Comment by pushfoo** [comment]
Ok, can you show me the driver tab of that dialog?

**Comment by Jalkhov** [comment]
![Screenshot_7](https://user-images.githubusercontent.com/36505934/115052677-370b8f00-9eac-11eb-983c-c759d4264512.png)

**Comment by pushfoo** [comment]
@benmoran56 @Jalkhov It might not actually be the driver not being absent. I've found similar issues reported for Kivy as recently as 2017 on hardware from a similar era. I don't understand the details very well yet, but it seems like older hardware reports the wrong opengl capabilities under windows 10 for some reason.

Here are some example issues mentioning it:

- https://github.com/kivy/kivy/issues/3576
- https://github.com/kivy/kivy/issues/5071
- https://stackoverflow.com/questions/34969990/kivy-does-not-detect-opengl-2-0

Interestingly, I also found a project on github that claims to collect workarounds for this, but I don't know if it's trustworthy. Someone more familiar with windows should take a look at this because I have no idea if it's legitimate: https://github.com/pal1000/save-legacy-intel-graphics

**Comment by Jalkhov** [comment]
I see, so shall I try that?

**Comment by pushfoo** [comment]
@Jalkhov Can you get on the pyglet discord server? I'm well out of my depth and discussing the issue with a knowledgable 
maintainer there.

**Comment by pushfoo** [comment]
I got sent this link, which seems to use reputable tools https://gist.github.com/rb-dahlb/26f316c5b6089807a139fc44ee69f0d1

I don't know if it will work for you, but it's worth a shot.

**Comment by caffeinepills** [comment]
https://www.intel.com/content/www/us/en/support/articles/000005526/graphics.html

Despite it saying UHD 620 (which normally is supported). According to Intel's site, Celeron 800 series graphics aren't supported on Windows 10. There are various workarounds that may or may not work, but bottom line is your hardware wasn't meant for Windows 10 despite them allowing you to upgrade to it. (Sadly)

**Comment by Jalkhov** [comment]
Ok, give me the linnk please

> I got sent this link, which seems to use reputable tools https://gist.github.com/rb-dahlb/26f316c5b6089807a139fc44ee69f0d1
> 
> I don't know if it will work for you, but it's worth a shot.

Ok, give me the link please.

**Comment by Jalkhov** [comment]
> https://www.intel.com/content/www/us/en/support/articles/000005526/graphics.html
> 
> Despite it saying UHD 620 (which normally is supported). According to Intel's site, Celeron 800 series graphics aren't supported on Windows 10. There are various workarounds (see above) that may or may not work, but bottom line is your hardware wasn't meant for Windows 10 despite them allowing you to upgrade to it. (Sadly)

t.t D*mn

**Comment by pushfoo** [comment]
@Jalkhov this is the guide https://gist.github.com/rb-dahlb/26f316c5b6089807a139fc44ee69f0d1

**Comment by Jalkhov** [comment]
> @Jalkhov this is the guide https://gist.github.com/rb-dahlb/26f316c5b6089807a139fc44ee69f0d1

Ok, I'm going to do it and I'll be letting you know the results. Thanks.

**Comment by Jalkhov** [comment]
![Screenshot_8](https://user-images.githubusercontent.com/36505934/115062497-6922ee00-9eb8-11eb-8f9c-e44cecef41a8.png)

Well...I have carried out the tutorial and...let's say it's half fixed, you can see the labels but now you can't see the sprites x.x

**Comment by pushfoo** [comment]
@caffeinepills Are there config arguments that could be set to address this or any other ideas you have?

@Jalkhov Sadly, there aren't any maintained drivers for hardware this old on Windows. We're already using unusual workarounds that aren't guaranteed to work. If there aren't any flags or settings that fix this on the current driver version, then you might be able to try downgrading the driver to the 8.1 version I linked earlier. 

Since you're on an old laptop, there's no viable way to replace the GPU with an add-in. However, if you're still determined to try to get pyglet working, you can try another OS by using a linux liveboot environment to test open gl behavior under it. Liveboot runs from a DVD or a USB drive without replacing your windows installation. If linux isn't something you want to try, you might be able to I think you might also be able to try contacting the original author of the windows 10 workaround for old intel graphics for help.

If caffienepills doesn't have any ideas and none of the above options work for you, then you might be able to use an SDL-backed drawing solution that doesn't rely on the GPU. That should work fine for simpler games and let you learn about games and python in the meantime.

**Comment by Jalkhov** [comment]
Ok I understand, I'll stop trying for now, I feel that even if I can solve this somehow, later on I might run into another problem x.x If the problem is the computer, I'd better leave it like this. Thanks for the help.

**Comment by pushfoo** [comment]
@Jalkhov No problem. Even if this turned out to be mostly unrelated to the other intel video issues I was trying to help solve, it has still helped me learn more about the libraries involved.

If you want to keep using windows, I can suggest two possible paths from here. I hope one is an acceptable option

### 1. Switch to an SDL-based framework

If SDL won't work, then it's likely nothing will. SDL is one of the most conservative and portable drawing, sound, and input handling libraries. I think you can even switch it into software rendering mode, and it will allow some basic features, even when the GPU has bad drivers. I've seen this work effectively when compiling and running [a project written in C](https://github.com/JohnEarnest/c-octo) on an older Raspberry Pi with outdated and broken graphics drivers installed.

For your specific needs writing what seems to be an asteroids game, I think you might want to try one of the following SDL-backed libraries:

- [pygame](https://www.pygame.org/) : a library with a long history. it gives you lot of control, but can be somewhat tedious to use at first. It is also famous for being very bad at drawing filled shapes. If you only want to draw sprites, then that flaw doesn't matter.
- [pygame zero](https://pygame-zero.readthedocs.io/en/stable/) : a wrapper around pygame that tries to make pygame more friendly to beginners at the price of making it harder to customize.

Neither seems to depend on any graphics library other than SDL. Personally, I would lean towards pygame zero if you want to get something working fast. If you can't get either to draw sprites correctly to the screen, you may need to revert the compatibility change you made during the tutorial. 

There's also the option of making raw SDL calls with [PySDL2](https://pypi.org/project/PySDL2/), but that seems like it would be a lot of hassle.

### 2. Revert compatibility changes & write your own text-rendering workaround for pyglet

This option might encounter something breaking down the line as you mentioned in your last post.

Since sprites worked before you used the open gl workaround, you might be able to revert it and use sprites to show text. I'm planning on using a similar workaround in another project for slightly different reasons. In short:

1. choose a monospace bitmap font to load
2. choose a starting position on the screen to display the string at
3. for each character in the string, create a sprite at `(start_x + i * glyph_width_px, start_y)` with a texture corresponding to the glyph you want to show
4. draw the sprites

To get you started, here's a font you could use:
![image](https://user-images.githubusercontent.com/36696816/115120063-781da500-9f79-11eb-84ba-7b598b2001ac.png)
_([Pixel Font by ElDuderino on opengameart.org](https://opengameart.org/content/pixel-font-basic-latin-latin-1-box-drawing))_

Both this font and the one it's based on are offered as public domain, so there are no license restrictions on use for commercial projects or any other purpose.

**Comment by Jalkhov** [comment]
I have used PyGame before, but I decided to migrate to Pyglet because honestly this last one seems to me quite better, not that PyGame is bad, but for my tastes and habits as a programmer, I adjusted better to Pyglet, but well, apparently I will have to go back to PyGame. However the option of using a bitmap font seems interesting to me, and could even result in something nicer, but I have no idea how to do this, if you could provide me with a link to read more about it I would appreciate it, if it is in the Pyglet docs much better.

**Comment by pushfoo** [comment]
It's not in the pyglet docs as far as I know. I'm suggesting you create your own class or function to manage arranging and drawing of whatever primitives pyglet uses to draw the contents of files on the screen. I might not have used the right terminology for pyglet because I have been using arcade, a framework built on top of pyglet with slightly different terminology for concepts. If that is the case, I aplogize. The pyglet discord might be able to help you figure out how to do what I am describing using the correct pyglet names, functions, and classes.

**Comment by Jalkhov** [comment]
All right, thank you very much for all the support, for my part this topic can be closed.

**Comment by pushfoo** [comment]
@benmoran56 @caffeinepills I think this ticket is ready to close unless you want to add any suggestions for the right classes and functions to use

**Comment by benmoran56** [comment]
@Jalkhov This may or may not work for you, but here is a crude example of making bitmapped fonts. 
This makes use of the `ImageGrid` class for splitting up the font image (the one that pushfoo posted earlier). 
The ImageGrid is indexable, so it's just using a matching string of text to find the right image to use: 

```py
class BitmappedTextLayout:

    def __init__(self, img, rows, columns, text_sequence, batch, group=None):
        self._img = img
        self._img_grid = pyglet.image.ImageGrid(self._img, rows, columns)
        self._text_seq = text_sequence
        self._batch = batch
        self._group = group

    def create_label(self, text, x, y):
        sprites = []
        for character in text:
            index = self._text_seq.find(character)
            img = self._img_grid[index]
            sprite = pyglet.sprite.Sprite(img, x, y, batch=self._batch, group=self._group)
            sprites.append(sprite)
            x += self._img_grid.item_width

        return sprites


font_img = pyglet.resource.image('monofont.png')
text_seq = r"""pqrstuvwxyz{|}~ `abcdefghijklmnoPQRSTUVWXYZ[\]^_@ABCDEFGHIJKLMNO0123456789:;<=>? !"#$%&'()*+,-./"""

layout = BitmappedTextLayout(font_img, 6, 16, text_seq, batch)

# make a label from it: 
label = layout.create_label("Hello, this is a test!", 100, 100)
```

**Comment by Jalkhov** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/36505934/115227028-eda28600-a0dd-11eb-8056-a412fab874e5.png)

Works 10, I think I will implement this to do something small at least while I migrate equipment, thank you very much @benmoran56 and others.

**Comment by benmoran56** [comment]
Great, I'm glad that helps. 

Also, as pushfoo mentioned, these graphics adapters are still well supported on Linux, so you might give that a try if you want to get a little more life out of your hardware.
