### ISSUE TITLE
Can't display some unicode sequences (triangles) after update to 1.5.16

### ISSUE THREAD

**Issue by benoitvalery** [pyglet/pyglet#382]
Hello,
With pyglet==1.5.16, some triangle unicode characters won't be displayed anymore. I'm using the pyglet.text.Label.
The char I want to display are the following : \u25b2 \u25BC \u25C0 \u25B6  (i.e., triangles).
Now pyglet is updated, these triangles are replaced by empty rectangle.

The first thing I tried is, following the MWE I found [here](https://pyglet.readthedocs.io/en/latest/programming_guide/text.html), to specify a font_name, which I didn't. But still, only \u25b2 & \u25BC are correctly displayed. \u25C0 & \u25B6 are still "empty rectangles".

Is it mandatory to specify the font_name to have these char rendered ? Why ?
I would like to avoid drawing it by hand (with GL_TRIANGLES for instance).

So, the following example should display only the first (UP and DOWN triangles, but not the lasting two), with pyglet 1.5.16.
I'm sorry but I don't know from which version of pyglet I came from...

```python
import pyglet
window = pyglet.window.Window()
label = pyglet.text.Label("\u25b2 \u25BC \u25C0 \u25B6",
                          font_name='Times New Roman',
                          font_size=36, color=(255,255,255,255),
                          x=window.width//2, y=window.height//2,
                          anchor_x='center', anchor_y='center')

@window.event
def on_draw():
    window.clear()
    label.draw()

pyglet.app.run()
```

Thanks for your help.

**Comment by benmoran56** [comment]
The square boxes are because the loaded font can't decode that particular character. 

Is this Linux? If so, the font decoding code hasn't changed, but it has always had some limitations. 
Linux uses a loader based on freetype. As long as freetype itself handles the characters, then the pyglet code could be improved to handle them as well. 

If this is Windows, then we recently added a new loader based on DirectWrite. This has much better support for special characters and emojis, but It's still new so it has to be enabled with the `pyglet.options['advanced_font_features'] = True` flag. 

In either case, some ttfs will work better than others. If you find a font that works with the characters, it can be a good idea to bundle that font with your application. The fonts can be added at runtime.

**Comment by benoitvalery** [comment]
I'm on Linux, Debian Bullseye. I will try some other fonts, but I'm troubled by the fact it has worked very well until now.

**Comment by benoitvalery** [comment]
On second thought, I think I will go with drawing the triangles in GL. Finally, it looks more robust to me. Thanks again for your advice.
