### ISSUE TITLE
Scaling for pyglet.gui widgets.

### ISSUE THREAD

**Issue by Ross-TheBoss** [pyglet/pyglet#416]
I think every widget in pyglet.gui should have **scale, scale_x and scale_y properties**. 

These properties would change the scale of all images the widget contains before drawing them to the screen. This would work in a similar way to how the pyglet.sprite module scales images.

Users of pyglet could use this feature to create GUIs for differing screen sizes.

**Comment by benmoran56** [comment]
I think this might be a little out of scope for this module.

Also, most UIs don't scale their widgets individually when the screen is resized.
For desktop applications, the widgets are usually just re-positioned when reshaping a Window.
For games, they tend to just scale the entire framebuffer, instead of individual components on the screen. Some games _do_ offer options to adjust the size of widgets separately from the base resolution, but that's the exception rather than the rule. In those cases, I'd argue that it's better to provide multiple images for the different sizes, and just change the widgets when adjusting the size.  For actual infinitely resizable widgets, it's probably best to make a custom object for that.

**Comment by einarf** [comment]
Scale with projection could work?

**Comment by benmoran56** [comment]
That's what I was thinking.

**Comment by Ross-TheBoss** [comment]
Can you scale them with a projection whilst still maintaining functionality (collision boxes update)?

**Comment by ShaunKulesa** [comment]
What I did is instead of batch drawing, I made a draw function in the widgets class and drawed each indivual item in that function. Then did widget.draw() that way you can update a size variable.

**Comment by ShaunKulesa** [comment]
@benmoran56
Every gui library I've used they allow you to change each widgets size indivually. And the only thing I do now is software development. So I know alot about gui.

**Comment by ShaunKulesa** [comment]
Also every gui library I've used has had a outline on each widget set by default to False and can be used by setting it to true.

**Comment by benmoran56** [comment]
pyglet isn't aiming to be a full featured GUI library, so unfortunately advanced features like this are out of scope.
The existence of the `pyglet.gui` module was really just to provide the very basics, that someone could potentially build on themselves. 

More advanced GUI features would be better suited for a third party library, and in fact there already existst a few. 
For example the Glooey library: 
https://github.com/kxgames/glooey

Thank you for opening the ticket and voicing your ideas!
