### ISSUE TITLE
unknow memory error

### ISSUE THREAD

**Issue by shenjackyuanjie** [pyglet/pyglet#476]
![5{(UP2FEN AK5TIPRF}VSPO](https://user-images.githubusercontent.com/54507071/135476785-2780c23a-eafa-450f-9aaf-555ca0c4a0ac.png)

don't know why
but the trace back shows that maybe something with memory
but i've thyed many times

PS: i'm running 3 minecraft java server and 2 Bungee Cord server when i run it
![8V7$LN4 NS%UR{~{G~0BD8H](https://user-images.githubusercontent.com/54507071/135477348-386900d3-c65d-480d-8957-593dca8ccc79.png)

**Comment by benmoran56** [comment]
It's difficult to guess what the issue is, because it's being returned from Windows. It does not seem to be generated inside of pyglet, which makes it difficult to help you. The "Access violation" error seems to be common with many different applications. 

My guess is that: 
1. Driver issue (cannot create so many OpenGL contexts on the same machine). 
2. Not enough system memory. 

If it's #2, maybe you can change the Minecraft JVM settings to use less memory?

**Comment by shenjackyuanjie** [comment]
hmmmm
this issue may not cause by pyglet
will close
