### ISSUE TITLE
Excessive Spikes of Star Shapes Not Drawing Correctly

### ISSUE THREAD

**Issue by eschan145** [pyglet/pyglet#646]
Using the pyglet's `shapes` module, I drew a star.
`Star(x=250, y=200, outer=30, inner=100, spikes=1000)`
![image](https://user-images.githubusercontent.com/103769713/178111386-11b24175-4e9c-4c15-8198-e335c79056b5.png)
I think there is a glitch here. Maybe I could use that do make patterns.

**Comment by benmoran56** [comment]
That's certainly an interesting pattern.

I'm not sure if I would call it a bug, because it's really just how OpenGL renders things. The inner and outer "rings" are inverted, and there aren't enough pixels to show everything. Things might become discernable if you zoomed in a bit, or maybe played with anti-aliasing.

We could maybe add an assertion to that class that checks that the outer diameter is larger than the inner. 🤔
