### ISSUE TITLE
can anyone modify draw diffent sprites ,or do it with a wapper c++lib like pysfml

### ISSUE THREAD

**Issue by zipandrar** [pyglet/pyglet#68]
def testSpriteUpdate():
    t1=time.clock()
    for body in logols:
        sprite.rotation = math.degrees(body.angle)
        sprite.position=body.position
    t2=time.clock()
    print len(logols),t2-t1

#len(logols)=200
#t2-t1=0.012s   in my win7 pentium(R) Dual-Core CPU E6700

#when i use the nuitka compile the sprite.py to sprite.pyd...
the 0.012s will reduce to 0.008s...

does there is any way to make it more quickly?

the second problem is
draw a batch with a same png sprite... is very very quickly.....

but draw different sprite with different png... is very slow just like draw one by one without the batch... although they are in a same batch...

pyglet is wonderful now and they are proper for making lots of games,but if anyone can draw different sprite as fast as pysfml(wapper c++) it will be great....

**Comment by caffeinepills** [comment]
1. There is no Cython wrapper for Pyglet. You mention the speed with pyglet, but failed to mention the other speed,, what is the difference in speed here? How quickly do you need it, exactly?

2. You shouldn't need to set rotation and position every frame unless they are constantly moving. Append/remove from your list if they are not moving to save unnecessary CPU cycles.

3. If you do need to set them every frame, setting `position` and setting `rotation` recalculates the vertices each time you assign values to them. To update multiple things at once, you want to do `sprite.update(x=x, y=y, rotation=rotation)` this will then only trigger the update of vertices once.

4. The issue with different images is, you are most likely using `pyglet.image.load` or `pyglet.resource.texture`, each of these creates a separate texture.

OpenGL requires you to change state everytime you change or bind a texture. Every state change is a separate draw call. So yes, if you had 100 images, and 100 different sprites, batch would be useless. If you want to load multiple images into one texture, use `pyglet.resource.image` instead of `pyglet.image.load`. This will try to pack the sprites into one texture to reduce draw calls.

Hope this helps.

**Comment by zipandrar** [comment]
#pysfml have no batch, but it is a wrapper of c++ sfml... so it is really quickly

ls = 1000 different png sprite...
t1=time.clock()
for i in ls:
....window.draw(i)
t2=time.clock()

t2-t1=0.019s


#update 1000 sprite's position is about 0.0045s
t3=time.clock()
for i in ls:
....i.position=x,y
t4=time.clock()
t4-t3=0.0045s

########
i even thought pyglet.resource.texture is as same as pyglet.image.load it is Just different ways of writing

you two tips will save a lot cpu........ thanks...

**Comment by zipandrar** [comment]
pysfml draw 1000 sprite cost a lot
and pyglet update position+rotation cost a lot...

pyglet even can closed to the c++ lib......  so powerful

**Comment by benmoran56** [comment]
I'm going to close this for now, since you got it working better. 
If you have more performance questions, you can visit our Discord server. There is a #HELP channel for asking questions.

**Comment by samnater** [comment]
3. If you do need to set them every frame, setting `position` and setting `rotation` recalculates the vertices each time you assign values to them. To update multiple things at once, you want to do `sprite.update(x=x, y=y, rotation=rotation)` this will then only trigger the update of vertices once.

Thank you! Changed my code and literally doubled my frame rate by doing that (see below). Going to read more into the details now haha sure there is more to learn.
from:
        self.x = self.orig_x + self.cam.loc_x
        self.y = self.orig_y + self.cam.loc_y
to:
        super().update(x=self.orig_x + self.cam.loc_x, y=self.orig_y + self.cam.loc_y)
