### ISSUE TITLE
pyglet freezes after an event crashes

### ISSUE THREAD

**Issue by csd4ni3l** [pyglet/pyglet#680]
pyglet freezes after an event crashes, by freezing i mean you cant exit you cant keyboard interrupt you can only kill the process, and because i use vscode i need to restart vscode for it and its really annoying

**Comment by benmoran56** [comment]
Events in pyglet are synchronous, and has no internal blocking code. If your event handlers hang, however, we can't prevent that on pyglet's side.

**Comment by csd4ni3l** [comment]
and what about a simple try except?

**Comment by benmoran56** [comment]
That's not enough to prevent hangs due to Threading or Multiprocessing.

If you're not already doing so, setting your threads or processes to "daemon" may help, but it's not guaranteed to be a solution. 
https://docs.python.org/3/library/threading.html#threading.Thread.daemon
https://docs.python.org/3/library/multiprocessing.html#multiprocessing.Process.daemon

This is not something we can prevent in pyglet, so I'll close this for now.
