### ISSUE TITLE
Vector `*` and `/` should be scalar operations

### ISSUE THREAD

**Issue by TomFryers** [pyglet/pyglet#685]
Having used `pygame.math.Vec2` quite a bit recently, this was the major pain point.

* `v.scale(2)` is a bit longer than `2 * v`.
* `v * w` is currently the element-wise product, which isn't a very common or useful operation, unlike scaling which is ubiquitous. (15 uses vs zero in my case.)
* When doing maths, we typically write something like **v** = 2**u** + 2**w**. This looks more similar to `v = 2 * u + 2 * w` than `v = u.scale(2) + w.scale(2)`. Element-wise product is usually **v** ⊙ **w**, but this rarely occurs, because it's not a particularly meaningful operation.
* `v * 2` = `2 * v`. `v / 2` is fine, but `2 / v` should probably be an error. Scaling down without `/` is a bit annoying, because one has to write `v.scale(1 / a)`
#### Other libraries
* Numpy arrays support both element-wise and scalar multiplication with `*`.
* `pygame.math.Vector2` uses `*` for both scalar multiplication and dot product. This is nice, but has a performance penalty.

**Comment by pushfoo** [comment]
I'm strongly in favor of this change. I didn't voice similar concerns because I thought the current behavior was kept for historical reasons. 2.X makes big breaking changes, and this is a minor compatibility hiccup by comparison. We could keep the `scale` method around if necessary to reduce the amount of update work needed.

**Comment by benmoran56** [comment]
Hi @TomFryers,
Thanks for opening the ticket, and for the detailed information. 
Even though gamedev specific math is not always the same as real math, 
I agree that it makes sense to change multiplication to scalar multiplication.

@pushfoo, 
We can probably just drop the `scale` method entirely, since we're still in dev releases. 
As for 1.5.x, the `math` module is an "undocumented feature". It was mainly ported back
just for extra testing for 2.0, so we're probably OK to make the same breaking changes
there as well. At some point in the future we can make it an official feature.

**Comment by benmoran56** [comment]
In the `master` branch, I went ahead and changed multiplication & division operations to be scalar by default.
I also dropped the `scale` method.  I'll have to decide what to do about 1.5, but I'm leaning towards backporting  the changes. 

Once we finalize the module after a bit more feedback, we can make it "official" in 1.5 as well by documenting it.
