### ISSUE TITLE
Pyglet is changing the tkinter.filedialog/file_explorer

### ISSUE THREAD

**Issue by Akascape** [pyglet/pyglet#692]
I am making a project combining both **Tkinter and Pyglet**, I have used a tkinter.filedialog but it is showing a weird behavior after using it with the pyglet window. Generally, tkinter.filedialog opens the native/modern file explorer of **windows** to browse the files but it is now showing an old looking explorer instead of the modern one. I don't know why this is happening, any fix to get back that file explorer?

Basic code to reproduce the issue:
```python
from tkinter import Tk, Button, filedialog
import pyglet
root= Tk()
root.geometry("200x100")
root.title("Tkiner_window")
window = pyglet.window.Window(20, 20, "Pyglet_window")
def open_file():
    file=filedialog.askopenfilename()
btn= Button(root, width=10,bg="#FFFFFF",fg="black", text="Open File",command=open_file)
btn.grid(padx=50,pady=20)
root.mainloop()
```

Moreover, other methods like `filedialog.askdirectory()` are not even working with this. 

### My Results:
![difference_filedialog](https://user-images.githubusercontent.com/89206401/194690821-12008a86-461b-49f6-b34e-2b74b245e60e.png)

**Comment by benmoran56** [comment]
Hi, 

Mixing pyglet with other Window libraries is not supported. You can make it work, but you need a deep understanding of both libraries. We do have one example of using Tkinter file dialogs here:
https://github.com/pyglet/pyglet/blob/master/examples/file_dialog.py

This works because the Tkinter code is run entirely in another process, and uses pyglet's event framework to asynchronously pass information back to pyglet. You may be able to use this example to make other Tkinter dialogs work as well.

Also, you can enable "file_drops" on pyglet Windows, allowing simple drag/drop events for simple use cases.
