### ISSUE TITLE
Breaking change due to v2.0.2.1 v.s. v1.15

### ISSUE THREAD

**Issue by neozhaoliang** [pyglet/pyglet#741]
Hi, it looks like in pyglet >= 2.0, `pyglet.image.Texture.create_for_size` is replaced by `pyglet.image.Texture.create`?  But after I updated this API call in my legacy code, the windows only showed a black screen without reporting any error. Is there anything I'm missing?

The code :

https://github.com/neozhaoliang/pywonderland/blob/master/src/shader-playground/wythoff_hyperbolic_tilings.py

This script runs fine with pyglet <= 1.15, but for pyglet >=2.0, I have to change this line:

https://github.com/neozhaoliang/pywonderland/blob/master/src/shader-playground/wythoff_hyperbolic_tilings.py#L76-L78

to

```python
self.iChannel0 = pyglet.image.Texture.create(
            width, height, gl.GL_TEXTURE_2D, gl.GL_RGBA32F
        )
```

But that doesn't show the animation as reported above.

**Comment by einarf** [comment]
Somewhat unrelated: It's a good idea to bump shader version to `#version 330` since this forces you to avoid using any deprecated stuff and you may avoid cross platform issues.

**Comment by benmoran56** [comment]
@neozhaoliang pyglet 2.0 now uses a GL 3.3 context by default. The old method was removed, because it was only for dealing with handling of pow2 and rectangle textures. 

Your project is fairly complex, and I was unable to see any specific reason why it's not working. I can see you are using GLSL 130 shaders as well as custom Shader classes. pyglet is requesting a 3.3 GL context by default, so it's possible some issue is arising from that. You could try to request a lower Context by using a custom gl.Config, but it would break some other things in pyglet (such as Sprites, Text/Labels). 

I would try to do a very minimal example using your Shader framework, to see if that's functional or not. 
pyglet does have built-in Shader support now, but it would probably be a lot of work to migrate your existing code to that.

**Comment by neozhaoliang** [comment]
@benmoran56 Thank you for this kindful reply! Yes, my shader framework is a bit lengthy, and I greatly appreciate your effort in looking into my code. @einarf  I tried changing the line `#version 130` to `#version 330` and `#version 330 core`, but still no animation and no errors.
I'd like to migrate my code to pyglet's built-in shader support, I didn't find enough information on the doc site, the example in the repo seems doesn't show how to bind multiple buffers and textures in one program.

**Comment by caffeinepills** [comment]
This may be because of the pyglet window having a default uniform block that handles view and projection matrix. You may need to add that to your own vertex shader, or change the default shader found here: https://github.com/pyglet/pyglet/blob/838d004d68fcc5c3ce83b733e3d088fad0643859/pyglet/window/__init__.py#L444

As far as framebuffer goes, you can find the code here https://github.com/pyglet/pyglet/blob/838d004d68fcc5c3ce83b733e3d088fad0643859/pyglet/image/buffer.py#L98 it could use an example or doc on it. It should be pretty straight forward.

**Comment by benmoran56** [comment]
In case it's useful, this example here shows making a Framebuffer, attaching a Texture to it, and rendering to that. 
https://github.com/pyglet/pyglet/blob/master/examples/window/fixed_resolution.py

**Comment by neozhaoliang** [comment]
@caffeinepills Changing the vertex shader (adding the `window` struct) doesn't work either. But I do can run `opengl_shader.py` in the examples folder.

The script `shader.py` in my repo is also widely used by many other projects, for example,
https://github.com/rougier/grayscott
So It would be great to know exactly what caused the problem.

@benmoran56 I see the example does the same job as the `framebuffer.py` I'm using here:
https://github.com/neozhaoliang/pywonderland/blob/master/src/glslhelpers/framebuffer.py
It would be great if there is a shadertoy work migrated to pyglet as an example.

**Comment by caffeinepills** [comment]
Your best bet then is to start with a small example that works as a base, and continue to add more to it until you find the discrepancy. It's possible there may be an issue somewhere or the shader just doesn't work for newer GLSL.

**Comment by neozhaoliang** [comment]
@caffeinepills No, I was too busy these days and had no time to look into that.

**Comment by caffeinepills** [comment]
No worries, re-open if you still have questions in the future.
