### ISSUE TITLE
accessibility on macOS

### ISSUE THREAD

**Issue by warshaya** [pyglet/pyglet#745]
Hello,

I'm trying to write an pyglet app on macOS, and was attempting to add ui testing using Appium ( https://appium.io/docs/en/drivers/mac2/ ) and also pyinstaller to set a bundleId ( https://pyinstaller.org/en/stable/usage.html#cmdoption-osx-bundle-identifier ) - however when I launch using Appium it does not see any accessibility from the app

```
[WebDriverAgentMac] [xcodebuild] t =     1.15s Open com.main.app
[WebDriverAgentMac] [xcodebuild] t =     1.15s     Launch com.main.app
[WebDriverAgentMac] [xcodebuild] t =     1.45s         Wait for accessibility to load
[WebDriverAgentMac] [xcodebuild] t =    61.45s             Capturing diagnostic spindump
[WebDriverAgentMac] [xcodebuild] /Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-mac2-driver/WebDriverAgentMac/WebDriverAgentRunner/WebDriverAgentRunner.m:48: error: -[UITestingUITests testRunner] : Application 'com.main.app' has not loaded accessibility
[WebDriverAgentMac] [xcodebuild] t =    76.98s         Setting up automation session
[HTTP] <-- POST /wd/hub/session - - ms - -
[HTTP] 
[WebDriverAgentMac] [xcodebuild] /Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-mac2-driver/WebDriverAgentMac/WebDriverAgentRunner/WebDriverAgentRunner.m:48: error: -[UITestingUITests testRunner] : Failed to get automation session for com.main.app:16287: Timed out while requesting automation session for com.main.app (pid:16287).
[WebDriverAgentMac] [xcodebuild] t =   146.01s         Wait for com.main.app to idle
```

Is there any setting or option in pyglet to enable accessibility on the cocoa components like Window? ( https://github.com/pyglet/pyglet/blob/a505dab72dc0e3ac5f44a43e0f4c7164b0c15a42/pyglet/window/cocoa/pyglet_window.py )

**Comment by caffeinepills** [comment]
This seems like a PyInstaller issue. However, I haven't been able to find anything that involves this and Cocoa, so I cannot say for sure.

Have you tried using Pyinstaller on this Appium without Pyglet to see if it's a Pyglet issue or just packaging with Pyinstaller?

**Comment by warshaya** [comment]
Previously I had tried using a Tk window, with Appium and PyInstaller, and Appium was able to find the window that way:

```
            main_window: WebElement = driver.find_element(
                by=AppiumBy.IOS_CLASS_CHAIN, value="**/XCUIElementTypeWindow"
            )

```

however when I switched the UI to pyglet, the Appium Server is having trouble to see that my PyInstaller-bundled app is launched.

Actually I can confirm accessibility is working on the hello_world.py example when I use these steps:

1. package the pyglet hello-world example:  `pyinstaller --windowed --osx-bundle-identifier "com.main.app" -y examples/hello_world.py` and run it.
2. open Xcode > Open Developer Tools > Accessibility Inspector - select the window.

This seems to be ok.  For my own project I was trying to implement my own event loop (based on https://pyglet.readthedocs.io/en/latest/programming_guide/eventloop.html#dispatching-events-manually ) - maybe that is causing the window's accessibility to go awry.  If I have some time I'll try to create a smaller demo app that I can share.

**Comment by benmoran56** [comment]
If you really cannot use pyglet's built-in event loop, you might have some success by starting and stepping the `PlatformEventLoop`. In pyglet, this is what handles keyboard/mouse events from the OS. It might be necessary in order to allow it to be recognized as a GUI application. There is a default instance of the PlatformEventLoop on the pyglet.app module:
```py
# call once to start the event loop
pyglet.app.platform_event_loop.start()
```
If that is not enough on it's own, you can try stepping the event loop. You must give it some timeout value, which is blocking. This is whatever idle time your application has in-between other scheduled events or drawing operations. In other words, whatever idle time you have in between each frame. 
```py
pyglet.app.platform_event_loop.step(timeout=idle_time_in_seconds)
```

You will probably also want to manually dispatch Window events, if you plan on receiving keyboard/mouse input. This section in the docs describes that in more detail:
https://pyglet.readthedocs.io/en/latest/programming_guide/eventloop.html#dispatching-events-manually
