### ISSUE TITLE
Allow rotation in Sprite constructor

### ISSUE THREAD

**Issue by DevilXD** [pyglet/pyglet#82]
Feature request - allow setting the rotation in the Sprite constructor

Here's how it'd work:
```py
# load an image of an arrow that points up by default
arrow = pyglet.image.load('arrow.png')
# set the rotation immediately in the constructor, so that the arrow points to the right
arrow_right = pyglet.sprite.Sprite(image, 20, 30, rotation=90)
```

Currently one has to do it like this:
```py
# load an image of an arrow that points up by default
arrow = pyglet.image.load('arrow.png')
# set the rotation in a second line, unnecessarily bloating the code
arrow_right = pyglet.sprite.Sprite(image, 20, 30)
arrow_right.rotation = 90
```

**Comment by caffeinepills** [comment]
IMO The initialization should just be the minimum of what's required to create the sprite. Setting rotation after the fact seems normal on what most engines would do. Could you provide a use case in which this adds a benefit?

**Comment by DevilXD** [comment]
I just did - it shortens the code. Settings this while creating a list is really cumbersome:
```py
self.snake = [
    Sprite(snake_head, 290, 290, batch=self.main_batch),
    Sprite(snake_body, 270, 290, batch=self.main_batch),
    Sprite(snake_body, 250, 290, batch=self.main_batch),
    Sprite(snake_body, 230, 290, batch=self.main_batch),
    Sprite(snake_tail, 210, 290, batch=self.main_batch),
]
self.snake[0].rotation = 90
```

This would be much better to do:
```py
self.snake = [
    Sprite(snake_head, 290, 290, batch=self.main_batch, rotation=90),
    Sprite(snake_body, 270, 290, batch=self.main_batch),
    Sprite(snake_body, 250, 290, batch=self.main_batch),
    Sprite(snake_body, 230, 290, batch=self.main_batch),
    Sprite(snake_tail, 210, 290, batch=self.main_batch),
]
```

It's just a convenience feature that makes the code shorter and cleaner, creating a sprite that already has the correct rotation afterwards, instead of requiring a second line to set. This also expands possibilities in list and dictionary comprehension creation - this is a single line:
```py
# nice and single line
flower = [Sprite(petal_img, 0, 0, rotation=r) for r in range(0, 360, 15)]
```
Normally, you'd need much more than that:
```py
# uh oh
flower = []
for r in range(0, 360, 15):
    petal = Sprite(petal_img, 0, 0)
    petal.rotation = r
    flower.append(petal)
```

**Comment by caffeinepills** [comment]
While I agree it does make it look cleaner, not entirely convinced it's the best fit. My thoughts are, I think adding this means `Sprite` would eventually have to have all of the attributes (color, opacity, scale, scale_x, scale_y, visible) into the constructor, either by request or just because it would look kind of strange to have rotation as the only one available. The benefits I can think of are, it would reduce the amount of calls to `_create_vertex_list` if you have lots of modifications to the sprite after creation. Doing some testing though, extra assigning all of those variables w/ kwargs would add a small performance penalty (20% from testing using timeit) . Maybe adding a new class `BaseSprite` vs `Sprite`? Not sure. 

Maybe Benjamin can chime in on how he views the initialization process of Sprites and if it's a good fit to do this.

Some alternatives I can think of:
`get_transform` will get you a copy of the transformed texture coordinates right from the image.

`arrow_right = pyglet.sprite.Sprite(image.get_transform(rotation=90), 20, 30)`

`self.snake = [
    Sprite(snake_head.get_transform(rotation=90), 290, 290, batch=self.main_batch),
    Sprite(snake_body, 270, 290, batch=self.main_batch),
    Sprite(snake_body, 250, 290, batch=self.main_batch),
    Sprite(snake_body, 230, 290, batch=self.main_batch),
    Sprite(snake_tail, 210, 290, batch=self.main_batch),
]`

Subclass the `pyglet.sprite.Sprite` and add your own constructors for your project for now.

**Comment by DevilXD** [comment]
```
AttributeError: 'ImageData' object has no attribute 'get_transform'
```
Do I need to convert it first somehow?

**Comment by caffeinepills** [comment]
Sorry, it looks like `get_transform` is for textures only. You could do `image.get_texture().get_transform(rotate=90)` or ```texture = image.get_texture()
texture.get_transform(rotate=90)
```

**Comment by benmoran56** [comment]
I'm afraid I agree with @caffeinepills here. If we add `rotation` as an initialization argument, we would have no argument against also adding scale, scale_x, scale_y, color, etc.   In my opinion it's best to keep it to a minimum. 

What you could do, is change the initial default rotation value:
`pyglet.sprite.Sprite._rotation = 90`
Obviously this would change it for all sprites, so maybe this is not what you want. 

In this situation I personally make utility functions for loading things with default values. For example:
```py
def create_sprite(image, x, y, rotation=0):
    spr = pyglet.sprite.Sprite(image, x, y)
    spr.rotation = rotation
    return spr
```

And for loading centered images, I do something like: 

```py
def load_image(filename, center_x=False, center_y=False):
    img = pyglet.resource.image(filename)
    if center_x:
        img.anchor_x = img.width // 2
    if center_y:
        img.anchor_y = img.height // 2
    return img```

**Comment by DevilXD** [comment]
Hmm, so just helper functions, I see. I guess I'll go with this instead.

For future reference and anyone who'd find this, you can use this initializer for a custom Sprite subclass, that will support this kwarg:
```py
class YourSprite(pyglet.sprite.Sprite):
    def __init__(self, image, *args, rotation=0, **kwargs):
        super().__init__(image.get_texture().get_transform(rotate=rotation), *args, **kwargs)
```
