### ISSUE TITLE
Pyglet.Shapes - Add Triangle And Line Rotation Support

### ISSUE THREAD

**Issue by nbroderick-code** [pyglet/pyglet#888]
**Is your feature request related to a problem? Please describe.**
When I set ".rotation" on a triangle or line, it does not rotate.

**Describe the solution you'd like**
I would like it to rotate these shapes around their center point instead of doing nothing because it isn't implemented.

I appreciate all your hard work! :)

**Comment by shenjackyuanjie** [comment]
Technically to implement `rotation` for triangle and line is simple
but here's the thing
which point should be the center?
the shape's first point?  the shape's geometry center? or some weird center you pointed out?
so which center?

**Comment by nbroderick-code** [comment]
The geometry's center is what most programs do, I think.

**Comment by pushfoo** [comment]
This came up again today [on Discord](https://discord.com/channels/438622377094414346/477394331112701952/1147648807622934590): `Circle` is also affected since it's an n-gon approximation.

I thought it had already been addressed, and apparently so did @caffeinepills :

> I think that makes sense to have some rotation even for circles. 
> Technically the circle could be multiple colors and if you want to spin it even.
> I thought all shapes had a rotation property

The simplest fix which comes to mind is moving this to `ShapeBase`, which I've partly addressed in #943.

To consider this issue finished, I think we need to support `rotation` as a keyword argument on all shapes. `Star` already supports it.

However, there is a problem:  `Line.__init__` sets the `rotation` from he slope of the points: 
https://github.com/pyglet/pyglet/blob/1af5a55f7aedac4a5245e7a306bb1c7cc1bdeda8/pyglet/shapes.py#L1102


How should we resolve Line's behavior? Options include:

1. `rotation: Optional[float] = None` as the rotation argument. If not `None`, override any inferred rotation from geometry data.
4. Remove the rotation keyword argument.
