### ISSUE TITLE
Feature Request: Provide IDE integration workarounds for ModuleProxy

### ISSUE THREAD

**Issue by pushfoo** [pyglet/pyglet#942]
### Feature request

Explore ways of enabling auto-complete despite the use of `ModuleProxy` for lazy loading. This is a low-priority edge case, but it would be a quality of life improvement when using `inspect` in the REPL.

### The Problem

tl;dr `ModuleProxy` instances interfere with autocomplete in PyCharm or the IDE

Example:
1. Open PyCharm's REPL
2. `from pyglet import shapes`
3. Attempt to access members of `shapes`
4. No autocomplete occurs

### Potential Solutions to Explore

- [x] Ship manually generated [`.pyi` files](https://peps.python.org/pep-0484/#stub-files)
- [ ] Ship auto-generated [`.pyi` files](https://peps.python.org/pep-0484/#stub-files)

**Comment by pushfoo** [comment]
This also seems to affect more regular usage such as auto-complete for key constants.

**Comment by caffeinepills** [comment]
I'm for including a manually generated stub file for the lazy loading. I use one and it does indeed do autocompletion with PyCharm.

The only caveat I can see in the future is if anyone were to do any sort of enforced loading type checking. Since this makes my  IDE (PyCharm) mark the `ModuleProxy`'s as an incorrect type.

**Comment by caffeinepills** [comment]
Stub file merged into master.
